// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package database

import (
	"context"
	"errors"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const markUnseenVariantsDelisted = `-- name: MarkUnseenVariantsDelisted :batchexec
update variants
set is_delisted = true, delisted_at = now(), updated_at = now()
where vendor_listing_id = $1
  and not is_delisted
  and last_seen_at < $2
`

type MarkUnseenVariantsDelistedBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type MarkUnseenVariantsDelistedParams struct {
	VendorListingID uuid.UUID          `json:"vendor_listing_id"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) MarkUnseenVariantsDelisted(ctx context.Context, arg []MarkUnseenVariantsDelistedParams) *MarkUnseenVariantsDelistedBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.VendorListingID,
			a.LastSeenAt,
		}
		batch.Queue(markUnseenVariantsDelisted, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &MarkUnseenVariantsDelistedBatchResults{br, len(arg), false}
}

func (b *MarkUnseenVariantsDelistedBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *MarkUnseenVariantsDelistedBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const setListingBasePriceFromVariants = `-- name: SetListingBasePriceFromVariants :batchexec
update vendor_listings
set previous_price = case
                         when sub.minimum_variant_price is distinct from vendor_listings.current_price
                             then vendor_listings.current_price
                         else vendor_listings.previous_price
                     end,
    price_last_changed_at = case
                         when vendor_listings.current_price is not null
                          and sub.minimum_variant_price is distinct from vendor_listings.current_price
                             then now()
                         else vendor_listings.price_last_changed_at
                     end,
    current_price  = sub.minimum_variant_price,
    updated_at     = now()
from (
    select min(current_price) as minimum_variant_price
    from variants
    where vendor_listing_id = $1 and not is_delisted and current_price is not null
) as sub
where vendor_listings.vendor_listing_id = $1
  and sub.minimum_variant_price is not null
`

type SetListingBasePriceFromVariantsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

// For a listing with variants the catalogue shows "from X", so the listing's
// own price tracks the cheapest live variant. This query owns all three price
// columns for such listings.
func (q *Queries) SetListingBasePriceFromVariants(ctx context.Context, vendorListingID []uuid.UUID) *SetListingBasePriceFromVariantsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range vendorListingID {
		vals := []interface{}{
			a,
		}
		batch.Queue(setListingBasePriceFromVariants, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &SetListingBasePriceFromVariantsBatchResults{br, len(vendorListingID), false}
}

func (b *SetListingBasePriceFromVariantsBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *SetListingBasePriceFromVariantsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertVariant = `-- name: UpsertVariant :batchexec
insert into variants (
    vendor_listing_id, variant_label, external_variant_id, variant_sku,
    is_in_stock, pack_size, current_price, last_seen_at
) values ($1, $2, $3, $4, $5, $6, $7, now())
on conflict (vendor_listing_id, variant_label) do update set
    external_variant_id = coalesce(excluded.external_variant_id, variants.external_variant_id),
    variant_sku         = coalesce(excluded.variant_sku, variants.variant_sku),
    is_in_stock         = excluded.is_in_stock,
    pack_size           = coalesce(excluded.pack_size, variants.pack_size),
    previous_price      = case
                              when excluded.current_price is distinct from variants.current_price
                                  then variants.current_price
                              else variants.previous_price
                          end,
    price_last_changed_at = case
                              when variants.current_price is not null
                               and excluded.current_price is distinct from variants.current_price
                                  then now()
                              else variants.price_last_changed_at
                          end,
    current_price       = excluded.current_price,
    is_delisted         = false,
    delisted_at         = null,
    last_seen_at        = now(),
    updated_at          = now()
`

type UpsertVariantBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertVariantParams struct {
	VendorListingID   uuid.UUID           `json:"vendor_listing_id"`
	VariantLabel      string              `json:"variant_label"`
	ExternalVariantID pgtype.Text         `json:"external_variant_id"`
	VariantSku        pgtype.Text         `json:"variant_sku"`
	IsInStock         bool                `json:"is_in_stock"`
	PackSize          pgtype.Int4         `json:"pack_size"`
	CurrentPrice      decimal.NullDecimal `json:"current_price"`
}

func (q *Queries) UpsertVariant(ctx context.Context, arg []UpsertVariantParams) *UpsertVariantBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.VendorListingID,
			a.VariantLabel,
			a.ExternalVariantID,
			a.VariantSku,
			a.IsInStock,
			a.PackSize,
			a.CurrentPrice,
		}
		batch.Queue(upsertVariant, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertVariantBatchResults{br, len(arg), false}
}

func (b *UpsertVariantBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertVariantBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertVendorListing = `-- name: UpsertVendorListing :batchone
insert into vendor_listings (
    vendor_id, product_url, external_product_id, listing_name, description,
    primary_image_url, vendor_side_category, vendor_side_sku,
    is_in_stock, has_variants, pack_size, current_price, last_seen_at
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now())
on conflict (vendor_id, product_url) do update set
    external_product_id  = coalesce(excluded.external_product_id, vendor_listings.external_product_id),
    listing_name         = excluded.listing_name,
    description          = coalesce(excluded.description, vendor_listings.description),
    primary_image_url    = coalesce(excluded.primary_image_url, vendor_listings.primary_image_url),
    vendor_side_category = coalesce(excluded.vendor_side_category, vendor_listings.vendor_side_category),
    vendor_side_sku      = coalesce(excluded.vendor_side_sku, vendor_listings.vendor_side_sku),
    is_in_stock          = excluded.is_in_stock,
    has_variants         = excluded.has_variants,
    pack_size            = coalesce(excluded.pack_size, vendor_listings.pack_size),
    previous_price       = case
                               when excluded.has_variants
                                   then vendor_listings.previous_price
                               when excluded.current_price is distinct from vendor_listings.current_price
                                   then vendor_listings.current_price
                               else vendor_listings.previous_price
                           end,
    -- A first sighting is not a price change: there was no prior price to move
    -- away from. Requiring a non-null old value keeps this stamp meaning "the
    -- vendor changed the price", which is how both the catalogue arrow and the
    -- scrape metrics read it.
    price_last_changed_at = case
                               when excluded.has_variants
                                   then vendor_listings.price_last_changed_at
                               when vendor_listings.current_price is not null
                                and excluded.current_price is distinct from vendor_listings.current_price
                                   then now()
                               else vendor_listings.price_last_changed_at
                           end,
    current_price        = case
                               when excluded.has_variants
                                   then vendor_listings.current_price
                               else excluded.current_price
                           end,
    is_delisted          = false,
    delisted_at          = null,
    last_seen_at         = now(),
    updated_at           = now()
returning vendor_listing_id, vendor_id, product_url, external_product_id, listing_name, description, primary_image_url, vendor_side_category, vendor_side_sku, is_in_stock, has_variants, is_tracked, is_delisted, delisted_at, last_seen_at, pack_size, current_price, previous_price, price_last_changed_at, created_at, updated_at
`

type UpsertVendorListingBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertVendorListingParams struct {
	VendorID           uuid.UUID           `json:"vendor_id"`
	ProductUrl         string              `json:"product_url"`
	ExternalProductID  pgtype.Text         `json:"external_product_id"`
	ListingName        string              `json:"listing_name"`
	Description        pgtype.Text         `json:"description"`
	PrimaryImageUrl    pgtype.Text         `json:"primary_image_url"`
	VendorSideCategory pgtype.Text         `json:"vendor_side_category"`
	VendorSideSku      pgtype.Text         `json:"vendor_side_sku"`
	IsInStock          bool                `json:"is_in_stock"`
	HasVariants        bool                `json:"has_variants"`
	PackSize           pgtype.Int4         `json:"pack_size"`
	CurrentPrice       decimal.NullDecimal `json:"current_price"`
}

// Note what is deliberately absent from the update list:
//
//	is_tracked  — the user's star, never touched by a scrape
//	pack_size   — coalesced, so a hand-entered value survives a scrape that
//	              could not detect one
//
// Price columns are owned by whoever knows the real price:
//   - a listing without variants prices itself here
//   - a listing WITH variants leaves all three price columns alone, because
//     SetListingBasePriceFromVariants derives them from the live variants.
//     Without that guard the upsert would blank current_price on every run
//     and the roll-up would restore it, churning previous_price and reporting
//     a price change on every scrape.
func (q *Queries) UpsertVendorListing(ctx context.Context, arg []UpsertVendorListingParams) *UpsertVendorListingBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.VendorID,
			a.ProductUrl,
			a.ExternalProductID,
			a.ListingName,
			a.Description,
			a.PrimaryImageUrl,
			a.VendorSideCategory,
			a.VendorSideSku,
			a.IsInStock,
			a.HasVariants,
			a.PackSize,
			a.CurrentPrice,
		}
		batch.Queue(upsertVendorListing, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertVendorListingBatchResults{br, len(arg), false}
}

func (b *UpsertVendorListingBatchResults) QueryRow(f func(int, VendorListing, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i VendorListing
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.VendorListingID,
			&i.VendorID,
			&i.ProductUrl,
			&i.ExternalProductID,
			&i.ListingName,
			&i.Description,
			&i.PrimaryImageUrl,
			&i.VendorSideCategory,
			&i.VendorSideSku,
			&i.IsInStock,
			&i.HasVariants,
			&i.IsTracked,
			&i.IsDelisted,
			&i.DelistedAt,
			&i.LastSeenAt,
			&i.PackSize,
			&i.CurrentPrice,
			&i.PreviousPrice,
			&i.PriceLastChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *UpsertVendorListingBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
