// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countVendorListings = `-- name: CountVendorListings :one

select count(*) from vendor_listings
where vendor_id = $1
  and (not $2::boolean or is_in_stock)
  and ($3::boolean or not is_delisted)
  and ($4::text = '' or listing_name ilike '%' || $4::text || '%')
`

type CountVendorListingsParams struct {
	VendorID        uuid.UUID `json:"vendor_id"`
	InStockOnly     bool      `json:"in_stock_only"`
	IncludeDelisted bool      `json:"include_delisted"`
	SearchText      string    `json:"search_text"`
}

// Queries backing P1: the vendor catalogue view and the listing content page.
func (q *Queries) CountVendorListings(ctx context.Context, arg CountVendorListingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVendorListings,
		arg.VendorID,
		arg.InStockOnly,
		arg.IncludeDelisted,
		arg.SearchText,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getListingAggregateRating = `-- name: GetListingAggregateRating :one
select coalesce(round(avg(rating)::numeric, 2), 0)::numeric(4, 2) as average_rating,
       count(rating)                                              as rating_count
from order_items
where vendor_listing_id = $1 and rating is not null
`

type GetListingAggregateRatingRow struct {
	AverageRating decimal.Decimal `json:"average_rating"`
	RatingCount   int64           `json:"rating_count"`
}

// BR-8a: a listing's rating is the average of the ratings given to order items
// referencing it, not a separately entered value. Computed on read so it can
// never go stale.
func (q *Queries) GetListingAggregateRating(ctx context.Context, vendorListingID uuid.NullUUID) (GetListingAggregateRatingRow, error) {
	row := q.db.QueryRow(ctx, getListingAggregateRating, vendorListingID)
	var i GetListingAggregateRatingRow
	err := row.Scan(&i.AverageRating, &i.RatingCount)
	return i, err
}

const listOrderItemsForListing = `-- name: ListOrderItemsForListing :many
select order_items.order_item_id, order_items.order_entry_id, order_items.vendor_listing_id, order_items.variant_id, order_items.vendor_id, order_items.listing_name_snapshot, order_items.quantity, order_items.price_per_unit, order_items.order_status, order_items.refund_amount, order_items.rating, order_items.created_at, order_items.updated_at,
       order_entries.ordered_on,
       order_entries.entry_name,
       variants.variant_label
from order_items
join order_entries on order_entries.order_entry_id = order_items.order_entry_id
left join variants on variants.variant_id = order_items.variant_id
where order_items.vendor_listing_id = $1
order by order_entries.ordered_on desc
`

type ListOrderItemsForListingRow struct {
	OrderItemID         uuid.UUID           `json:"order_item_id"`
	OrderEntryID        uuid.UUID           `json:"order_entry_id"`
	VendorListingID     uuid.NullUUID       `json:"vendor_listing_id"`
	VariantID           uuid.NullUUID       `json:"variant_id"`
	VendorID            uuid.UUID           `json:"vendor_id"`
	ListingNameSnapshot string              `json:"listing_name_snapshot"`
	Quantity            int32               `json:"quantity"`
	PricePerUnit        decimal.Decimal     `json:"price_per_unit"`
	OrderStatus         string              `json:"order_status"`
	RefundAmount        decimal.NullDecimal `json:"refund_amount"`
	Rating              pgtype.Int4         `json:"rating"`
	CreatedAt           pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	OrderedOn           pgtype.Date         `json:"ordered_on"`
	EntryName           pgtype.Text         `json:"entry_name"`
	VariantLabel        pgtype.Text         `json:"variant_label"`
}

// FR-P1-9: every past purchase of this specific listing, with what was paid.
func (q *Queries) ListOrderItemsForListing(ctx context.Context, vendorListingID uuid.NullUUID) ([]ListOrderItemsForListingRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsForListing, vendorListingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsForListingRow{}
	for rows.Next() {
		var i ListOrderItemsForListingRow
		if err := rows.Scan(
			&i.OrderItemID,
			&i.OrderEntryID,
			&i.VendorListingID,
			&i.VariantID,
			&i.VendorID,
			&i.ListingNameSnapshot,
			&i.Quantity,
			&i.PricePerUnit,
			&i.OrderStatus,
			&i.RefundAmount,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderedOn,
			&i.EntryName,
			&i.VariantLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedListings = `-- name: ListTrackedListings :many
select vendor_listings.vendor_listing_id, vendor_listings.vendor_id, vendor_listings.product_url, vendor_listings.external_product_id, vendor_listings.listing_name, vendor_listings.description, vendor_listings.primary_image_url, vendor_listings.vendor_side_category, vendor_listings.vendor_side_sku, vendor_listings.is_in_stock, vendor_listings.has_variants, vendor_listings.is_tracked, vendor_listings.is_delisted, vendor_listings.delisted_at, vendor_listings.last_seen_at, vendor_listings.pack_size, vendor_listings.current_price, vendor_listings.previous_price, vendor_listings.price_last_changed_at, vendor_listings.created_at, vendor_listings.updated_at, vendors.vendor_name, vendors.vendor_slug,
       (select count(*) from variants
         where variants.vendor_listing_id = vendor_listings.vendor_listing_id
           and not variants.is_delisted) as variant_count
from vendor_listings
join vendors on vendors.vendor_id = vendor_listings.vendor_id
where vendor_listings.is_tracked and not vendor_listings.is_delisted
order by vendors.vendor_name, vendor_listings.listing_name
`

type ListTrackedListingsRow struct {
	VendorListingID    uuid.UUID           `json:"vendor_listing_id"`
	VendorID           uuid.UUID           `json:"vendor_id"`
	ProductUrl         string              `json:"product_url"`
	ExternalProductID  pgtype.Text         `json:"external_product_id"`
	ListingName        string              `json:"listing_name"`
	Description        pgtype.Text         `json:"description"`
	PrimaryImageUrl    pgtype.Text         `json:"primary_image_url"`
	VendorSideCategory pgtype.Text         `json:"vendor_side_category"`
	VendorSideSku      pgtype.Text         `json:"vendor_side_sku"`
	IsInStock          bool                `json:"is_in_stock"`
	HasVariants        bool                `json:"has_variants"`
	IsTracked          bool                `json:"is_tracked"`
	IsDelisted         bool                `json:"is_delisted"`
	DelistedAt         pgtype.Timestamptz  `json:"delisted_at"`
	LastSeenAt         pgtype.Timestamptz  `json:"last_seen_at"`
	PackSize           pgtype.Int4         `json:"pack_size"`
	CurrentPrice       decimal.NullDecimal `json:"current_price"`
	PreviousPrice      decimal.NullDecimal `json:"previous_price"`
	PriceLastChangedAt pgtype.Timestamptz  `json:"price_last_changed_at"`
	CreatedAt          pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `json:"updated_at"`
	VendorName         string              `json:"vendor_name"`
	VendorSlug         string              `json:"vendor_slug"`
	VariantCount       int64               `json:"variant_count"`
}

func (q *Queries) ListTrackedListings(ctx context.Context) ([]ListTrackedListingsRow, error) {
	rows, err := q.db.Query(ctx, listTrackedListings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrackedListingsRow{}
	for rows.Next() {
		var i ListTrackedListingsRow
		if err := rows.Scan(
			&i.VendorListingID,
			&i.VendorID,
			&i.ProductUrl,
			&i.ExternalProductID,
			&i.ListingName,
			&i.Description,
			&i.PrimaryImageUrl,
			&i.VendorSideCategory,
			&i.VendorSideSku,
			&i.IsInStock,
			&i.HasVariants,
			&i.IsTracked,
			&i.IsDelisted,
			&i.DelistedAt,
			&i.LastSeenAt,
			&i.PackSize,
			&i.CurrentPrice,
			&i.PreviousPrice,
			&i.PriceLastChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorName,
			&i.VendorSlug,
			&i.VariantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorListings = `-- name: ListVendorListings :many
select vendor_listings.vendor_listing_id, vendor_listings.vendor_id, vendor_listings.product_url, vendor_listings.external_product_id, vendor_listings.listing_name, vendor_listings.description, vendor_listings.primary_image_url, vendor_listings.vendor_side_category, vendor_listings.vendor_side_sku, vendor_listings.is_in_stock, vendor_listings.has_variants, vendor_listings.is_tracked, vendor_listings.is_delisted, vendor_listings.delisted_at, vendor_listings.last_seen_at, vendor_listings.pack_size, vendor_listings.current_price, vendor_listings.previous_price, vendor_listings.price_last_changed_at, vendor_listings.created_at, vendor_listings.updated_at,
       (select count(*) from variants
         where variants.vendor_listing_id = vendor_listings.vendor_listing_id
           and not variants.is_delisted) as variant_count
from vendor_listings
where vendor_id = $1
  and (not $2::boolean or is_in_stock)
  and ($3::boolean or not is_delisted)
  and ($4::text = '' or listing_name ilike '%' || $4::text || '%')
order by listing_name
limit $6 offset $5
`

type ListVendorListingsParams struct {
	VendorID        uuid.UUID `json:"vendor_id"`
	InStockOnly     bool      `json:"in_stock_only"`
	IncludeDelisted bool      `json:"include_delisted"`
	SearchText      string    `json:"search_text"`
	ResultOffset    int32     `json:"result_offset"`
	ResultLimit     int32     `json:"result_limit"`
}

type ListVendorListingsRow struct {
	VendorListingID    uuid.UUID           `json:"vendor_listing_id"`
	VendorID           uuid.UUID           `json:"vendor_id"`
	ProductUrl         string              `json:"product_url"`
	ExternalProductID  pgtype.Text         `json:"external_product_id"`
	ListingName        string              `json:"listing_name"`
	Description        pgtype.Text         `json:"description"`
	PrimaryImageUrl    pgtype.Text         `json:"primary_image_url"`
	VendorSideCategory pgtype.Text         `json:"vendor_side_category"`
	VendorSideSku      pgtype.Text         `json:"vendor_side_sku"`
	IsInStock          bool                `json:"is_in_stock"`
	HasVariants        bool                `json:"has_variants"`
	IsTracked          bool                `json:"is_tracked"`
	IsDelisted         bool                `json:"is_delisted"`
	DelistedAt         pgtype.Timestamptz  `json:"delisted_at"`
	LastSeenAt         pgtype.Timestamptz  `json:"last_seen_at"`
	PackSize           pgtype.Int4         `json:"pack_size"`
	CurrentPrice       decimal.NullDecimal `json:"current_price"`
	PreviousPrice      decimal.NullDecimal `json:"previous_price"`
	PriceLastChangedAt pgtype.Timestamptz  `json:"price_last_changed_at"`
	CreatedAt          pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `json:"updated_at"`
	VariantCount       int64               `json:"variant_count"`
}

// The catalogue never hides an out-of-stock or delisted listing on its own
// (BR-15); the filters here are driven by the user's own controls.
//
// current_price and previous_price come back as they are stored, so the client
// can draw the price-change arrow (FR-P1-2) without a second query.
func (q *Queries) ListVendorListings(ctx context.Context, arg ListVendorListingsParams) ([]ListVendorListingsRow, error) {
	rows, err := q.db.Query(ctx, listVendorListings,
		arg.VendorID,
		arg.InStockOnly,
		arg.IncludeDelisted,
		arg.SearchText,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVendorListingsRow{}
	for rows.Next() {
		var i ListVendorListingsRow
		if err := rows.Scan(
			&i.VendorListingID,
			&i.VendorID,
			&i.ProductUrl,
			&i.ExternalProductID,
			&i.ListingName,
			&i.Description,
			&i.PrimaryImageUrl,
			&i.VendorSideCategory,
			&i.VendorSideSku,
			&i.IsInStock,
			&i.HasVariants,
			&i.IsTracked,
			&i.IsDelisted,
			&i.DelistedAt,
			&i.LastSeenAt,
			&i.PackSize,
			&i.CurrentPrice,
			&i.PreviousPrice,
			&i.PriceLastChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VariantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
