// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compare.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const addCompareEntryListingMember = `-- name: AddCompareEntryListingMember :one
insert into compare_entry_members (compare_entry_id, vendor_listing_id)
values ($1, $2)
on conflict (compare_entry_id, vendor_listing_id) where vendor_listing_id is not null
do update set added_at = compare_entry_members.added_at
returning compare_entry_member_id, compare_entry_id, vendor_listing_id, variant_id, added_at
`

type AddCompareEntryListingMemberParams struct {
	CompareEntryID  uuid.UUID     `json:"compare_entry_id"`
	VendorListingID uuid.NullUUID `json:"vendor_listing_id"`
}

// BR-1: the same listing may sit in many compare entries, so a clash here is
// only ever the same listing added to the same entry twice.
func (q *Queries) AddCompareEntryListingMember(ctx context.Context, arg AddCompareEntryListingMemberParams) (CompareEntryMember, error) {
	row := q.db.QueryRow(ctx, addCompareEntryListingMember, arg.CompareEntryID, arg.VendorListingID)
	var i CompareEntryMember
	err := row.Scan(
		&i.CompareEntryMemberID,
		&i.CompareEntryID,
		&i.VendorListingID,
		&i.VariantID,
		&i.AddedAt,
	)
	return i, err
}

const addCompareEntryVariantMember = `-- name: AddCompareEntryVariantMember :one
insert into compare_entry_members (compare_entry_id, variant_id)
values ($1, $2)
on conflict (compare_entry_id, variant_id) where variant_id is not null
do update set added_at = compare_entry_members.added_at
returning compare_entry_member_id, compare_entry_id, vendor_listing_id, variant_id, added_at
`

type AddCompareEntryVariantMemberParams struct {
	CompareEntryID uuid.UUID     `json:"compare_entry_id"`
	VariantID      uuid.NullUUID `json:"variant_id"`
}

func (q *Queries) AddCompareEntryVariantMember(ctx context.Context, arg AddCompareEntryVariantMemberParams) (CompareEntryMember, error) {
	row := q.db.QueryRow(ctx, addCompareEntryVariantMember, arg.CompareEntryID, arg.VariantID)
	var i CompareEntryMember
	err := row.Scan(
		&i.CompareEntryMemberID,
		&i.CompareEntryID,
		&i.VendorListingID,
		&i.VariantID,
		&i.AddedAt,
	)
	return i, err
}

const createCompareEntry = `-- name: CreateCompareEntry :one
insert into compare_entries (entry_name) values ($1) returning compare_entry_id, entry_name, created_at, updated_at
`

func (q *Queries) CreateCompareEntry(ctx context.Context, entryName string) (CompareEntry, error) {
	row := q.db.QueryRow(ctx, createCompareEntry, entryName)
	var i CompareEntry
	err := row.Scan(
		&i.CompareEntryID,
		&i.EntryName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompareEntry = `-- name: DeleteCompareEntry :exec
delete from compare_entries where compare_entry_id = $1
`

// BR-17: only ever manual. Nothing in the system deletes a compare entry.
func (q *Queries) DeleteCompareEntry(ctx context.Context, compareEntryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompareEntry, compareEntryID)
	return err
}

const deleteCompareEntryMember = `-- name: DeleteCompareEntryMember :exec
delete from compare_entry_members
where compare_entry_id = $1 and compare_entry_member_id = $2
`

type DeleteCompareEntryMemberParams struct {
	CompareEntryID       uuid.UUID `json:"compare_entry_id"`
	CompareEntryMemberID uuid.UUID `json:"compare_entry_member_id"`
}

func (q *Queries) DeleteCompareEntryMember(ctx context.Context, arg DeleteCompareEntryMemberParams) error {
	_, err := q.db.Exec(ctx, deleteCompareEntryMember, arg.CompareEntryID, arg.CompareEntryMemberID)
	return err
}

const getCompareEntry = `-- name: GetCompareEntry :one
select compare_entry_id, entry_name, created_at, updated_at from compare_entries where compare_entry_id = $1
`

func (q *Queries) GetCompareEntry(ctx context.Context, compareEntryID uuid.UUID) (CompareEntry, error) {
	row := q.db.QueryRow(ctx, getCompareEntry, compareEntryID)
	var i CompareEntry
	err := row.Scan(
		&i.CompareEntryID,
		&i.EntryName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompareEntries = `-- name: ListCompareEntries :many

select compare_entries.compare_entry_id, compare_entries.entry_name, compare_entries.created_at, compare_entries.updated_at,
       (select count(*) from compare_entry_members
         where compare_entry_members.compare_entry_id = compare_entries.compare_entry_id
       ) as member_count
from compare_entries
order by compare_entries.created_at desc
`

type ListCompareEntriesRow struct {
	CompareEntryID uuid.UUID          `json:"compare_entry_id"`
	EntryName      string             `json:"entry_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	MemberCount    int64              `json:"member_count"`
}

// Queries backing P2: compare entries.
func (q *Queries) ListCompareEntries(ctx context.Context) ([]ListCompareEntriesRow, error) {
	rows, err := q.db.Query(ctx, listCompareEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompareEntriesRow{}
	for rows.Next() {
		var i ListCompareEntriesRow
		if err := rows.Scan(
			&i.CompareEntryID,
			&i.EntryName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompareEntryMembers = `-- name: ListCompareEntryMembers :many
select compare_entry_members.compare_entry_member_id,
       compare_entry_members.added_at,
       compare_entry_members.variant_id,
       vendor_listings.vendor_listing_id,
       vendor_listings.listing_name,
       vendor_listings.product_url,
       vendor_listings.primary_image_url,
       vendor_listings.is_in_stock,
       vendor_listings.is_delisted,
       vendor_listings.pack_size    as listing_pack_size,
       vendor_listings.current_price as listing_current_price,
       vendors.vendor_name,
       vendors.vendor_slug,
       variants.variant_label,
       variants.pack_size            as variant_pack_size,
       variants.current_price        as variant_current_price,
       variants.is_in_stock          as variant_is_in_stock
from compare_entry_members
left join variants on variants.variant_id = compare_entry_members.variant_id
join vendor_listings on vendor_listings.vendor_listing_id =
     coalesce(compare_entry_members.vendor_listing_id, variants.vendor_listing_id)
join vendors on vendors.vendor_id = vendor_listings.vendor_id
where compare_entry_members.compare_entry_id = $1
order by vendors.vendor_name, vendor_listings.listing_name
`

type ListCompareEntryMembersRow struct {
	CompareEntryMemberID uuid.UUID           `json:"compare_entry_member_id"`
	AddedAt              pgtype.Timestamptz  `json:"added_at"`
	VariantID            uuid.NullUUID       `json:"variant_id"`
	VendorListingID      uuid.UUID           `json:"vendor_listing_id"`
	ListingName          string              `json:"listing_name"`
	ProductUrl           string              `json:"product_url"`
	PrimaryImageUrl      pgtype.Text         `json:"primary_image_url"`
	IsInStock            bool                `json:"is_in_stock"`
	IsDelisted           bool                `json:"is_delisted"`
	ListingPackSize      pgtype.Int4         `json:"listing_pack_size"`
	ListingCurrentPrice  decimal.NullDecimal `json:"listing_current_price"`
	VendorName           string              `json:"vendor_name"`
	VendorSlug           string              `json:"vendor_slug"`
	VariantLabel         pgtype.Text         `json:"variant_label"`
	VariantPackSize      pgtype.Int4         `json:"variant_pack_size"`
	VariantCurrentPrice  decimal.NullDecimal `json:"variant_current_price"`
	VariantIsInStock     pgtype.Bool         `json:"variant_is_in_stock"`
}

// A member points at either a listing or one of its variants. The listing is
// resolved either way so the comparison table always has a name, image and
// vendor to show.
func (q *Queries) ListCompareEntryMembers(ctx context.Context, compareEntryID uuid.UUID) ([]ListCompareEntryMembersRow, error) {
	rows, err := q.db.Query(ctx, listCompareEntryMembers, compareEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompareEntryMembersRow{}
	for rows.Next() {
		var i ListCompareEntryMembersRow
		if err := rows.Scan(
			&i.CompareEntryMemberID,
			&i.AddedAt,
			&i.VariantID,
			&i.VendorListingID,
			&i.ListingName,
			&i.ProductUrl,
			&i.PrimaryImageUrl,
			&i.IsInStock,
			&i.IsDelisted,
			&i.ListingPackSize,
			&i.ListingCurrentPrice,
			&i.VendorName,
			&i.VendorSlug,
			&i.VariantLabel,
			&i.VariantPackSize,
			&i.VariantCurrentPrice,
			&i.VariantIsInStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCompareEntry = `-- name: RenameCompareEntry :one
update compare_entries set entry_name = $2, updated_at = now()
where compare_entry_id = $1 returning compare_entry_id, entry_name, created_at, updated_at
`

type RenameCompareEntryParams struct {
	CompareEntryID uuid.UUID `json:"compare_entry_id"`
	EntryName      string    `json:"entry_name"`
}

func (q *Queries) RenameCompareEntry(ctx context.Context, arg RenameCompareEntryParams) (CompareEntry, error) {
	row := q.db.QueryRow(ctx, renameCompareEntry, arg.CompareEntryID, arg.EntryName)
	var i CompareEntry
	err := row.Scan(
		&i.CompareEntryID,
		&i.EntryName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
