// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVariantByID = `-- name: GetVariantByID :one
select variant_id, vendor_listing_id, variant_label, external_variant_id, variant_sku, is_in_stock, is_delisted, delisted_at, last_seen_at, pack_size, current_price, previous_price, price_last_changed_at, created_at, updated_at from variants where variant_id = $1
`

func (q *Queries) GetVariantByID(ctx context.Context, variantID uuid.UUID) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariantByID, variantID)
	var i Variant
	err := row.Scan(
		&i.VariantID,
		&i.VendorListingID,
		&i.VariantLabel,
		&i.ExternalVariantID,
		&i.VariantSku,
		&i.IsInStock,
		&i.IsDelisted,
		&i.DelistedAt,
		&i.LastSeenAt,
		&i.PackSize,
		&i.CurrentPrice,
		&i.PreviousPrice,
		&i.PriceLastChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorListingByID = `-- name: GetVendorListingByID :one
select vendor_listing_id, vendor_id, product_url, external_product_id, listing_name, description, primary_image_url, vendor_side_category, vendor_side_sku, is_in_stock, has_variants, is_tracked, is_delisted, delisted_at, last_seen_at, pack_size, current_price, previous_price, price_last_changed_at, created_at, updated_at, detail_fetched_at from vendor_listings where vendor_listing_id = $1
`

func (q *Queries) GetVendorListingByID(ctx context.Context, vendorListingID uuid.UUID) (VendorListing, error) {
	row := q.db.QueryRow(ctx, getVendorListingByID, vendorListingID)
	var i VendorListing
	err := row.Scan(
		&i.VendorListingID,
		&i.VendorID,
		&i.ProductUrl,
		&i.ExternalProductID,
		&i.ListingName,
		&i.Description,
		&i.PrimaryImageUrl,
		&i.VendorSideCategory,
		&i.VendorSideSku,
		&i.IsInStock,
		&i.HasVariants,
		&i.IsTracked,
		&i.IsDelisted,
		&i.DelistedAt,
		&i.LastSeenAt,
		&i.PackSize,
		&i.CurrentPrice,
		&i.PreviousPrice,
		&i.PriceLastChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DetailFetchedAt,
	)
	return i, err
}

const getVendorListingsByIDs = `-- name: GetVendorListingsByIDs :many
select vendor_listing_id, vendor_id, product_url, external_product_id, listing_name, description, primary_image_url, vendor_side_category, vendor_side_sku, is_in_stock, has_variants, is_tracked, is_delisted, delisted_at, last_seen_at, pack_size, current_price, previous_price, price_last_changed_at, created_at, updated_at, detail_fetched_at from vendor_listings where vendor_listing_id = any($1::uuid[])
`

// The roll-up above rewrites price columns, so the scraper re-reads what it
// just wrote. One query for the whole chunk rather than one per listing.
func (q *Queries) GetVendorListingsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]VendorListing, error) {
	rows, err := q.db.Query(ctx, getVendorListingsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorListing{}
	for rows.Next() {
		var i VendorListing
		if err := rows.Scan(
			&i.VendorListingID,
			&i.VendorID,
			&i.ProductUrl,
			&i.ExternalProductID,
			&i.ListingName,
			&i.Description,
			&i.PrimaryImageUrl,
			&i.VendorSideCategory,
			&i.VendorSideSku,
			&i.IsInStock,
			&i.HasVariants,
			&i.IsTracked,
			&i.IsDelisted,
			&i.DelistedAt,
			&i.LastSeenAt,
			&i.PackSize,
			&i.CurrentPrice,
			&i.PreviousPrice,
			&i.PriceLastChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DetailFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingsNeedingDetail = `-- name: ListListingsNeedingDetail :many
select vendor_listing_id, vendor_id, product_url, external_product_id, listing_name, description, primary_image_url, vendor_side_category, vendor_side_sku, is_in_stock, has_variants, is_tracked, is_delisted, delisted_at, last_seen_at, pack_size, current_price, previous_price, price_last_changed_at, created_at, updated_at, detail_fetched_at from vendor_listings
where vendor_id = $1
  and not is_delisted
  and (detail_fetched_at is null or detail_fetched_at < $2)
order by detail_fetched_at nulls first, listing_name
limit $3
`

type ListListingsNeedingDetailParams struct {
	VendorID    uuid.UUID          `json:"vendor_id"`
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
	ResultLimit int32              `json:"result_limit"`
}

// Listings whose product page has never been read, or was read longest ago.
//
// Only some vendors keep anything on the product page, so this is called only
// for those. Never-read listings come first: a listing with no options at all
// is more wrong than one whose options are a few days old.
func (q *Queries) ListListingsNeedingDetail(ctx context.Context, arg ListListingsNeedingDetailParams) ([]VendorListing, error) {
	rows, err := q.db.Query(ctx, listListingsNeedingDetail, arg.VendorID, arg.StaleBefore, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorListing{}
	for rows.Next() {
		var i VendorListing
		if err := rows.Scan(
			&i.VendorListingID,
			&i.VendorID,
			&i.ProductUrl,
			&i.ExternalProductID,
			&i.ListingName,
			&i.Description,
			&i.PrimaryImageUrl,
			&i.VendorSideCategory,
			&i.VendorSideSku,
			&i.IsInStock,
			&i.HasVariants,
			&i.IsTracked,
			&i.IsDelisted,
			&i.DelistedAt,
			&i.LastSeenAt,
			&i.PackSize,
			&i.CurrentPrice,
			&i.PreviousPrice,
			&i.PriceLastChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DetailFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedListingsForVendor = `-- name: ListTrackedListingsForVendor :many
select vendor_listing_id, vendor_id, product_url, external_product_id, listing_name, description, primary_image_url, vendor_side_category, vendor_side_sku, is_in_stock, has_variants, is_tracked, is_delisted, delisted_at, last_seen_at, pack_size, current_price, previous_price, price_last_changed_at, created_at, updated_at, detail_fetched_at from vendor_listings
where vendor_id = $1 and is_tracked and not is_delisted
order by listing_name
`

func (q *Queries) ListTrackedListingsForVendor(ctx context.Context, vendorID uuid.UUID) ([]VendorListing, error) {
	rows, err := q.db.Query(ctx, listTrackedListingsForVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorListing{}
	for rows.Next() {
		var i VendorListing
		if err := rows.Scan(
			&i.VendorListingID,
			&i.VendorID,
			&i.ProductUrl,
			&i.ExternalProductID,
			&i.ListingName,
			&i.Description,
			&i.PrimaryImageUrl,
			&i.VendorSideCategory,
			&i.VendorSideSku,
			&i.IsInStock,
			&i.HasVariants,
			&i.IsTracked,
			&i.IsDelisted,
			&i.DelistedAt,
			&i.LastSeenAt,
			&i.PackSize,
			&i.CurrentPrice,
			&i.PreviousPrice,
			&i.PriceLastChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DetailFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsForListing = `-- name: ListVariantsForListing :many
select variant_id, vendor_listing_id, variant_label, external_variant_id, variant_sku, is_in_stock, is_delisted, delisted_at, last_seen_at, pack_size, current_price, previous_price, price_last_changed_at, created_at, updated_at from variants
where vendor_listing_id = $1 and not is_delisted
order by variant_label
`

func (q *Queries) ListVariantsForListing(ctx context.Context, vendorListingID uuid.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariantsForListing, vendorListingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variant{}
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.VariantID,
			&i.VendorListingID,
			&i.VariantLabel,
			&i.ExternalVariantID,
			&i.VariantSku,
			&i.IsInStock,
			&i.IsDelisted,
			&i.DelistedAt,
			&i.LastSeenAt,
			&i.PackSize,
			&i.CurrentPrice,
			&i.PreviousPrice,
			&i.PriceLastChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markListingDetailFetched = `-- name: MarkListingDetailFetched :exec
update vendor_listings set detail_fetched_at = now(), updated_at = now()
where vendor_listing_id = $1
`

func (q *Queries) MarkListingDetailFetched(ctx context.Context, vendorListingID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markListingDetailFetched, vendorListingID)
	return err
}

const markUnseenListingsDelisted = `-- name: MarkUnseenListingsDelisted :execrows
update vendor_listings
set is_delisted = true, delisted_at = now(), updated_at = now()
where vendor_id = $1
  and not is_delisted
  and last_seen_at < $2
`

type MarkUnseenListingsDelistedParams struct {
	VendorID   uuid.UUID          `json:"vendor_id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

// Anything not touched since this run started is gone from the vendor's site.
// Soft delete only: price history and past orders must survive.
func (q *Queries) MarkUnseenListingsDelisted(ctx context.Context, arg MarkUnseenListingsDelistedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markUnseenListingsDelisted, arg.VendorID, arg.LastSeenAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setListingTracked = `-- name: SetListingTracked :one
update vendor_listings
set is_tracked = $2, updated_at = now()
where vendor_listing_id = $1
returning vendor_listing_id, vendor_id, product_url, external_product_id, listing_name, description, primary_image_url, vendor_side_category, vendor_side_sku, is_in_stock, has_variants, is_tracked, is_delisted, delisted_at, last_seen_at, pack_size, current_price, previous_price, price_last_changed_at, created_at, updated_at, detail_fetched_at
`

type SetListingTrackedParams struct {
	VendorListingID uuid.UUID `json:"vendor_listing_id"`
	IsTracked       bool      `json:"is_tracked"`
}

func (q *Queries) SetListingTracked(ctx context.Context, arg SetListingTrackedParams) (VendorListing, error) {
	row := q.db.QueryRow(ctx, setListingTracked, arg.VendorListingID, arg.IsTracked)
	var i VendorListing
	err := row.Scan(
		&i.VendorListingID,
		&i.VendorID,
		&i.ProductUrl,
		&i.ExternalProductID,
		&i.ListingName,
		&i.Description,
		&i.PrimaryImageUrl,
		&i.VendorSideCategory,
		&i.VendorSideSku,
		&i.IsInStock,
		&i.HasVariants,
		&i.IsTracked,
		&i.IsDelisted,
		&i.DelistedAt,
		&i.LastSeenAt,
		&i.PackSize,
		&i.CurrentPrice,
		&i.PreviousPrice,
		&i.PriceLastChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DetailFetchedAt,
	)
	return i, err
}
