// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const addOrderItemCategoryTag = `-- name: AddOrderItemCategoryTag :exec
insert into order_item_category_tags (order_item_id, category_id)
values ($1, $2) on conflict do nothing
`

type AddOrderItemCategoryTagParams struct {
	OrderItemID uuid.UUID `json:"order_item_id"`
	CategoryID  uuid.UUID `json:"category_id"`
}

func (q *Queries) AddOrderItemCategoryTag(ctx context.Context, arg AddOrderItemCategoryTagParams) error {
	_, err := q.db.Exec(ctx, addOrderItemCategoryTag, arg.OrderItemID, arg.CategoryID)
	return err
}

const addOrderItemOccasionTag = `-- name: AddOrderItemOccasionTag :exec
insert into order_item_occasion_tags (order_item_id, occasion_tag_id)
values ($1, $2) on conflict do nothing
`

type AddOrderItemOccasionTagParams struct {
	OrderItemID   uuid.UUID `json:"order_item_id"`
	OccasionTagID uuid.UUID `json:"occasion_tag_id"`
}

func (q *Queries) AddOrderItemOccasionTag(ctx context.Context, arg AddOrderItemOccasionTagParams) error {
	_, err := q.db.Exec(ctx, addOrderItemOccasionTag, arg.OrderItemID, arg.OccasionTagID)
	return err
}

const clearOrderItemCategoryTags = `-- name: ClearOrderItemCategoryTags :exec
delete from order_item_category_tags where order_item_id = $1
`

func (q *Queries) ClearOrderItemCategoryTags(ctx context.Context, orderItemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearOrderItemCategoryTags, orderItemID)
	return err
}

const clearOrderItemOccasionTags = `-- name: ClearOrderItemOccasionTags :exec
delete from order_item_occasion_tags where order_item_id = $1
`

func (q *Queries) ClearOrderItemOccasionTags(ctx context.Context, orderItemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearOrderItemOccasionTags, orderItemID)
	return err
}

const createOrderEntry = `-- name: CreateOrderEntry :one
insert into order_entries (entry_name, ordered_on) values ($1, $2) returning order_entry_id, entry_name, ordered_on, created_at, updated_at
`

type CreateOrderEntryParams struct {
	EntryName pgtype.Text `json:"entry_name"`
	OrderedOn pgtype.Date `json:"ordered_on"`
}

func (q *Queries) CreateOrderEntry(ctx context.Context, arg CreateOrderEntryParams) (OrderEntry, error) {
	row := q.db.QueryRow(ctx, createOrderEntry, arg.EntryName, arg.OrderedOn)
	var i OrderEntry
	err := row.Scan(
		&i.OrderEntryID,
		&i.EntryName,
		&i.OrderedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
insert into order_items (
    order_entry_id, vendor_listing_id, variant_id, vendor_id,
    listing_name_snapshot, quantity, price_per_unit,
    order_status, refund_amount, rating
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
returning order_item_id, order_entry_id, vendor_listing_id, variant_id, vendor_id, listing_name_snapshot, quantity, price_per_unit, order_status, refund_amount, rating, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderEntryID        uuid.UUID           `json:"order_entry_id"`
	VendorListingID     uuid.NullUUID       `json:"vendor_listing_id"`
	VariantID           uuid.NullUUID       `json:"variant_id"`
	VendorID            uuid.UUID           `json:"vendor_id"`
	ListingNameSnapshot string              `json:"listing_name_snapshot"`
	Quantity            int32               `json:"quantity"`
	PricePerUnit        decimal.Decimal     `json:"price_per_unit"`
	OrderStatus         string              `json:"order_status"`
	RefundAmount        decimal.NullDecimal `json:"refund_amount"`
	Rating              pgtype.Int4         `json:"rating"`
}

// BR-7: price_per_unit is what was actually paid, entered by the user, never
// copied from the current scraped price.
func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderEntryID,
		arg.VendorListingID,
		arg.VariantID,
		arg.VendorID,
		arg.ListingNameSnapshot,
		arg.Quantity,
		arg.PricePerUnit,
		arg.OrderStatus,
		arg.RefundAmount,
		arg.Rating,
	)
	var i OrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderEntryID,
		&i.VendorListingID,
		&i.VariantID,
		&i.VendorID,
		&i.ListingNameSnapshot,
		&i.Quantity,
		&i.PricePerUnit,
		&i.OrderStatus,
		&i.RefundAmount,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrderEntry = `-- name: DeleteOrderEntry :exec
delete from order_entries where order_entry_id = $1
`

func (q *Queries) DeleteOrderEntry(ctx context.Context, orderEntryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderEntry, orderEntryID)
	return err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
delete from order_items where order_item_id = $1
`

func (q *Queries) DeleteOrderItem(ctx context.Context, orderItemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrderItem, orderItemID)
	return err
}

const getOrderEntry = `-- name: GetOrderEntry :one
select order_entries.order_entry_id, order_entries.entry_name, order_entries.ordered_on, order_entries.created_at, order_entries.updated_at,
       coalesce(sum(order_items.quantity * order_items.price_per_unit), 0)::numeric(14, 2) as total_cost,
       count(order_items.order_item_id)                                                    as item_count
from order_entries
left join order_items on order_items.order_entry_id = order_entries.order_entry_id
where order_entries.order_entry_id = $1
group by order_entries.order_entry_id
`

type GetOrderEntryRow struct {
	OrderEntryID uuid.UUID          `json:"order_entry_id"`
	EntryName    pgtype.Text        `json:"entry_name"`
	OrderedOn    pgtype.Date        `json:"ordered_on"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TotalCost    decimal.Decimal    `json:"total_cost"`
	ItemCount    int64              `json:"item_count"`
}

func (q *Queries) GetOrderEntry(ctx context.Context, orderEntryID uuid.UUID) (GetOrderEntryRow, error) {
	row := q.db.QueryRow(ctx, getOrderEntry, orderEntryID)
	var i GetOrderEntryRow
	err := row.Scan(
		&i.OrderEntryID,
		&i.EntryName,
		&i.OrderedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalCost,
		&i.ItemCount,
	)
	return i, err
}

const getOrderItem = `-- name: GetOrderItem :one
select order_item_id, order_entry_id, vendor_listing_id, variant_id, vendor_id, listing_name_snapshot, quantity, price_per_unit, order_status, refund_amount, rating, created_at, updated_at from order_items where order_item_id = $1
`

func (q *Queries) GetOrderItem(ctx context.Context, orderItemID uuid.UUID) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItem, orderItemID)
	var i OrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderEntryID,
		&i.VendorListingID,
		&i.VariantID,
		&i.VendorID,
		&i.ListingNameSnapshot,
		&i.Quantity,
		&i.PricePerUnit,
		&i.OrderStatus,
		&i.RefundAmount,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoryTagsForOrderItem = `-- name: ListCategoryTagsForOrderItem :many
select categories.category_id, categories.category_name, categories.is_system, categories.created_at from categories
join order_item_category_tags on order_item_category_tags.category_id = categories.category_id
where order_item_category_tags.order_item_id = $1
order by categories.category_name
`

func (q *Queries) ListCategoryTagsForOrderItem(ctx context.Context, orderItemID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoryTagsForOrderItem, orderItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccasionTagsForOrderItem = `-- name: ListOccasionTagsForOrderItem :many
select occasion_tags.occasion_tag_id, occasion_tags.tag_name, occasion_tags.created_at from occasion_tags
join order_item_occasion_tags on order_item_occasion_tags.occasion_tag_id = occasion_tags.occasion_tag_id
where order_item_occasion_tags.order_item_id = $1
order by occasion_tags.tag_name
`

func (q *Queries) ListOccasionTagsForOrderItem(ctx context.Context, orderItemID uuid.UUID) ([]OccasionTag, error) {
	rows, err := q.db.Query(ctx, listOccasionTagsForOrderItem, orderItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OccasionTag{}
	for rows.Next() {
		var i OccasionTag
		if err := rows.Scan(&i.OccasionTagID, &i.TagName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderEntries = `-- name: ListOrderEntries :many

select order_entries.order_entry_id, order_entries.entry_name, order_entries.ordered_on, order_entries.created_at, order_entries.updated_at,
       coalesce(sum(order_items.quantity * order_items.price_per_unit), 0)::numeric(14, 2) as total_cost,
       count(order_items.order_item_id)                                                    as item_count
from order_entries
left join order_items on order_items.order_entry_id = order_entries.order_entry_id
group by order_entries.order_entry_id
order by order_entries.ordered_on desc, order_entries.created_at desc
`

type ListOrderEntriesRow struct {
	OrderEntryID uuid.UUID          `json:"order_entry_id"`
	EntryName    pgtype.Text        `json:"entry_name"`
	OrderedOn    pgtype.Date        `json:"ordered_on"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TotalCost    decimal.Decimal    `json:"total_cost"`
	ItemCount    int64              `json:"item_count"`
}

// Queries backing P3: order entries and order items.
// BR-9: total_cost is never stored, always derived.
func (q *Queries) ListOrderEntries(ctx context.Context) ([]ListOrderEntriesRow, error) {
	rows, err := q.db.Query(ctx, listOrderEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderEntriesRow{}
	for rows.Next() {
		var i ListOrderEntriesRow
		if err := rows.Scan(
			&i.OrderEntryID,
			&i.EntryName,
			&i.OrderedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCost,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsForEntry = `-- name: ListOrderItemsForEntry :many
select order_items.order_item_id, order_items.order_entry_id, order_items.vendor_listing_id, order_items.variant_id, order_items.vendor_id, order_items.listing_name_snapshot, order_items.quantity, order_items.price_per_unit, order_items.order_status, order_items.refund_amount, order_items.rating, order_items.created_at, order_items.updated_at,
       vendors.vendor_name,
       vendors.vendor_slug,
       variants.variant_label,
       vendor_listings.product_url,
       vendor_listings.primary_image_url
from order_items
join vendors on vendors.vendor_id = order_items.vendor_id
left join variants on variants.variant_id = order_items.variant_id
left join vendor_listings on vendor_listings.vendor_listing_id = order_items.vendor_listing_id
where order_items.order_entry_id = $1
order by order_items.created_at
`

type ListOrderItemsForEntryRow struct {
	OrderItemID         uuid.UUID           `json:"order_item_id"`
	OrderEntryID        uuid.UUID           `json:"order_entry_id"`
	VendorListingID     uuid.NullUUID       `json:"vendor_listing_id"`
	VariantID           uuid.NullUUID       `json:"variant_id"`
	VendorID            uuid.UUID           `json:"vendor_id"`
	ListingNameSnapshot string              `json:"listing_name_snapshot"`
	Quantity            int32               `json:"quantity"`
	PricePerUnit        decimal.Decimal     `json:"price_per_unit"`
	OrderStatus         string              `json:"order_status"`
	RefundAmount        decimal.NullDecimal `json:"refund_amount"`
	Rating              pgtype.Int4         `json:"rating"`
	CreatedAt           pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
	VendorName          string              `json:"vendor_name"`
	VendorSlug          string              `json:"vendor_slug"`
	VariantLabel        pgtype.Text         `json:"variant_label"`
	ProductUrl          pgtype.Text         `json:"product_url"`
	PrimaryImageUrl     pgtype.Text         `json:"primary_image_url"`
}

func (q *Queries) ListOrderItemsForEntry(ctx context.Context, orderEntryID uuid.UUID) ([]ListOrderItemsForEntryRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsForEntry, orderEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsForEntryRow{}
	for rows.Next() {
		var i ListOrderItemsForEntryRow
		if err := rows.Scan(
			&i.OrderItemID,
			&i.OrderEntryID,
			&i.VendorListingID,
			&i.VariantID,
			&i.VendorID,
			&i.ListingNameSnapshot,
			&i.Quantity,
			&i.PricePerUnit,
			&i.OrderStatus,
			&i.RefundAmount,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorName,
			&i.VendorSlug,
			&i.VariantLabel,
			&i.ProductUrl,
			&i.PrimaryImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderEntry = `-- name: UpdateOrderEntry :one
update order_entries set entry_name = $2, ordered_on = $3, updated_at = now()
where order_entry_id = $1 returning order_entry_id, entry_name, ordered_on, created_at, updated_at
`

type UpdateOrderEntryParams struct {
	OrderEntryID uuid.UUID   `json:"order_entry_id"`
	EntryName    pgtype.Text `json:"entry_name"`
	OrderedOn    pgtype.Date `json:"ordered_on"`
}

func (q *Queries) UpdateOrderEntry(ctx context.Context, arg UpdateOrderEntryParams) (OrderEntry, error) {
	row := q.db.QueryRow(ctx, updateOrderEntry, arg.OrderEntryID, arg.EntryName, arg.OrderedOn)
	var i OrderEntry
	err := row.Scan(
		&i.OrderEntryID,
		&i.EntryName,
		&i.OrderedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderItem = `-- name: UpdateOrderItem :one
update order_items set
    vendor_listing_id     = $2,
    variant_id            = $3,
    vendor_id             = $4,
    listing_name_snapshot = $5,
    quantity              = $6,
    price_per_unit        = $7,
    order_status          = $8,
    refund_amount         = $9,
    rating                = $10,
    updated_at            = now()
where order_item_id = $1
returning order_item_id, order_entry_id, vendor_listing_id, variant_id, vendor_id, listing_name_snapshot, quantity, price_per_unit, order_status, refund_amount, rating, created_at, updated_at
`

type UpdateOrderItemParams struct {
	OrderItemID         uuid.UUID           `json:"order_item_id"`
	VendorListingID     uuid.NullUUID       `json:"vendor_listing_id"`
	VariantID           uuid.NullUUID       `json:"variant_id"`
	VendorID            uuid.UUID           `json:"vendor_id"`
	ListingNameSnapshot string              `json:"listing_name_snapshot"`
	Quantity            int32               `json:"quantity"`
	PricePerUnit        decimal.Decimal     `json:"price_per_unit"`
	OrderStatus         string              `json:"order_status"`
	RefundAmount        decimal.NullDecimal `json:"refund_amount"`
	Rating              pgtype.Int4         `json:"rating"`
}

func (q *Queries) UpdateOrderItem(ctx context.Context, arg UpdateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, updateOrderItem,
		arg.OrderItemID,
		arg.VendorListingID,
		arg.VariantID,
		arg.VendorID,
		arg.ListingNameSnapshot,
		arg.Quantity,
		arg.PricePerUnit,
		arg.OrderStatus,
		arg.RefundAmount,
		arg.Rating,
	)
	var i OrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderEntryID,
		&i.VendorListingID,
		&i.VariantID,
		&i.VendorID,
		&i.ListingNameSnapshot,
		&i.Quantity,
		&i.PricePerUnit,
		&i.OrderStatus,
		&i.RefundAmount,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
