// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sale_orders.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createSaleOrderCategory = `-- name: CreateSaleOrderCategory :one
insert into sale_order_categories (category_name) values ($1) returning sale_order_category_id, category_name, is_system, created_at
`

func (q *Queries) CreateSaleOrderCategory(ctx context.Context, categoryName string) (SaleOrderCategory, error) {
	row := q.db.QueryRow(ctx, createSaleOrderCategory, categoryName)
	var i SaleOrderCategory
	err := row.Scan(
		&i.SaleOrderCategoryID,
		&i.CategoryName,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createSaleOrderEntry = `-- name: CreateSaleOrderEntry :one
insert into sale_order_entries (
    sale_order_id, consumer_name, order_placed_date,
    order_status, delivered_date, sale_order_category_id
) values ($1, $2, $3, $4, $5, $6)
returning sale_order_entry_id, sale_order_id, consumer_name, order_placed_date, order_status, delivered_date, sale_order_category_id, created_at, updated_at
`

type CreateSaleOrderEntryParams struct {
	SaleOrderID         int32       `json:"sale_order_id"`
	ConsumerName        string      `json:"consumer_name"`
	OrderPlacedDate     pgtype.Date `json:"order_placed_date"`
	OrderStatus         string      `json:"order_status"`
	DeliveredDate       pgtype.Date `json:"delivered_date"`
	SaleOrderCategoryID uuid.UUID   `json:"sale_order_category_id"`
}

// BR-21: sale_order_id is supplied by the handler, which picks a free four-to
// six-digit number and retries if the unique index rejects it.
func (q *Queries) CreateSaleOrderEntry(ctx context.Context, arg CreateSaleOrderEntryParams) (SaleOrderEntry, error) {
	row := q.db.QueryRow(ctx, createSaleOrderEntry,
		arg.SaleOrderID,
		arg.ConsumerName,
		arg.OrderPlacedDate,
		arg.OrderStatus,
		arg.DeliveredDate,
		arg.SaleOrderCategoryID,
	)
	var i SaleOrderEntry
	err := row.Scan(
		&i.SaleOrderEntryID,
		&i.SaleOrderID,
		&i.ConsumerName,
		&i.OrderPlacedDate,
		&i.OrderStatus,
		&i.DeliveredDate,
		&i.SaleOrderCategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSaleOrderItem = `-- name: CreateSaleOrderItem :one
insert into sale_order_items (sale_order_entry_id, product_name, quantity, price_per_unit)
values ($1, $2, $3, $4)
returning sale_order_item_id, sale_order_entry_id, product_name, quantity, price_per_unit, created_at, updated_at
`

type CreateSaleOrderItemParams struct {
	SaleOrderEntryID uuid.UUID       `json:"sale_order_entry_id"`
	ProductName      string          `json:"product_name"`
	Quantity         int32           `json:"quantity"`
	PricePerUnit     decimal.Decimal `json:"price_per_unit"`
}

func (q *Queries) CreateSaleOrderItem(ctx context.Context, arg CreateSaleOrderItemParams) (SaleOrderItem, error) {
	row := q.db.QueryRow(ctx, createSaleOrderItem,
		arg.SaleOrderEntryID,
		arg.ProductName,
		arg.Quantity,
		arg.PricePerUnit,
	)
	var i SaleOrderItem
	err := row.Scan(
		&i.SaleOrderItemID,
		&i.SaleOrderEntryID,
		&i.ProductName,
		&i.Quantity,
		&i.PricePerUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllNonSystemSaleOrderCategories = `-- name: DeleteAllNonSystemSaleOrderCategories :exec
delete from sale_order_categories where not is_system
`

func (q *Queries) DeleteAllNonSystemSaleOrderCategories(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllNonSystemSaleOrderCategories)
	return err
}

const deleteAllSaleOrderEntries = `-- name: DeleteAllSaleOrderEntries :exec

delete from sale_order_entries
`

// Data wipe (BR-14). Sales are the user's own records exactly as purchases
// are, so a wipe that left them behind would not be the wipe it promises.
func (q *Queries) DeleteAllSaleOrderEntries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllSaleOrderEntries)
	return err
}

const deleteSaleOrderCategory = `-- name: DeleteSaleOrderCategory :exec
delete from sale_order_categories where sale_order_category_id = $1
`

func (q *Queries) DeleteSaleOrderCategory(ctx context.Context, saleOrderCategoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSaleOrderCategory, saleOrderCategoryID)
	return err
}

const deleteSaleOrderEntry = `-- name: DeleteSaleOrderEntry :exec
delete from sale_order_entries where sale_order_entry_id = $1
`

func (q *Queries) DeleteSaleOrderEntry(ctx context.Context, saleOrderEntryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSaleOrderEntry, saleOrderEntryID)
	return err
}

const deleteSaleOrderItem = `-- name: DeleteSaleOrderItem :exec
delete from sale_order_items where sale_order_item_id = $1
`

func (q *Queries) DeleteSaleOrderItem(ctx context.Context, saleOrderItemID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSaleOrderItem, saleOrderItemID)
	return err
}

const getSaleOrderCategoryByName = `-- name: GetSaleOrderCategoryByName :one
select sale_order_category_id, category_name, is_system, created_at from sale_order_categories where category_name = $1
`

func (q *Queries) GetSaleOrderCategoryByName(ctx context.Context, categoryName string) (SaleOrderCategory, error) {
	row := q.db.QueryRow(ctx, getSaleOrderCategoryByName, categoryName)
	var i SaleOrderCategory
	err := row.Scan(
		&i.SaleOrderCategoryID,
		&i.CategoryName,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getSaleOrderEntry = `-- name: GetSaleOrderEntry :one
select sale_order_entries.sale_order_entry_id, sale_order_entries.sale_order_id, sale_order_entries.consumer_name, sale_order_entries.order_placed_date, sale_order_entries.order_status, sale_order_entries.delivered_date, sale_order_entries.sale_order_category_id, sale_order_entries.created_at, sale_order_entries.updated_at,
       sale_order_categories.category_name,
       coalesce(sum(sale_order_items.quantity * sale_order_items.price_per_unit), 0)::numeric(14, 2)
           as total_amount,
       count(sale_order_items.sale_order_item_id) as item_count
from sale_order_entries
join sale_order_categories
     on sale_order_categories.sale_order_category_id = sale_order_entries.sale_order_category_id
left join sale_order_items
     on sale_order_items.sale_order_entry_id = sale_order_entries.sale_order_entry_id
where sale_order_entries.sale_order_entry_id = $1
group by sale_order_entries.sale_order_entry_id, sale_order_categories.category_name
`

type GetSaleOrderEntryRow struct {
	SaleOrderEntryID    uuid.UUID          `json:"sale_order_entry_id"`
	SaleOrderID         int32              `json:"sale_order_id"`
	ConsumerName        string             `json:"consumer_name"`
	OrderPlacedDate     pgtype.Date        `json:"order_placed_date"`
	OrderStatus         string             `json:"order_status"`
	DeliveredDate       pgtype.Date        `json:"delivered_date"`
	SaleOrderCategoryID uuid.UUID          `json:"sale_order_category_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CategoryName        string             `json:"category_name"`
	TotalAmount         decimal.Decimal    `json:"total_amount"`
	ItemCount           int64              `json:"item_count"`
}

func (q *Queries) GetSaleOrderEntry(ctx context.Context, saleOrderEntryID uuid.UUID) (GetSaleOrderEntryRow, error) {
	row := q.db.QueryRow(ctx, getSaleOrderEntry, saleOrderEntryID)
	var i GetSaleOrderEntryRow
	err := row.Scan(
		&i.SaleOrderEntryID,
		&i.SaleOrderID,
		&i.ConsumerName,
		&i.OrderPlacedDate,
		&i.OrderStatus,
		&i.DeliveredDate,
		&i.SaleOrderCategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.TotalAmount,
		&i.ItemCount,
	)
	return i, err
}

const getSaleOrderItem = `-- name: GetSaleOrderItem :one
select sale_order_item_id, sale_order_entry_id, product_name, quantity, price_per_unit, created_at, updated_at from sale_order_items where sale_order_item_id = $1
`

func (q *Queries) GetSaleOrderItem(ctx context.Context, saleOrderItemID uuid.UUID) (SaleOrderItem, error) {
	row := q.db.QueryRow(ctx, getSaleOrderItem, saleOrderItemID)
	var i SaleOrderItem
	err := row.Scan(
		&i.SaleOrderItemID,
		&i.SaleOrderEntryID,
		&i.ProductName,
		&i.Quantity,
		&i.PricePerUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSaleOrderCategories = `-- name: ListSaleOrderCategories :many

select sale_order_categories.sale_order_category_id, sale_order_categories.category_name, sale_order_categories.is_system, sale_order_categories.created_at,
       (select count(*) from sale_order_entries
         where sale_order_entries.sale_order_category_id
               = sale_order_categories.sale_order_category_id) as usage_count
from sale_order_categories
order by sale_order_categories.is_system desc, sale_order_categories.category_name
`

type ListSaleOrderCategoriesRow struct {
	SaleOrderCategoryID uuid.UUID          `json:"sale_order_category_id"`
	CategoryName        string             `json:"category_name"`
	IsSystem            bool               `json:"is_system"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UsageCount          int64              `json:"usage_count"`
}

// ── Sale order categories (FR-P5-4, BR-23) ───────────────────────────────
func (q *Queries) ListSaleOrderCategories(ctx context.Context) ([]ListSaleOrderCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listSaleOrderCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSaleOrderCategoriesRow{}
	for rows.Next() {
		var i ListSaleOrderCategoriesRow
		if err := rows.Scan(
			&i.SaleOrderCategoryID,
			&i.CategoryName,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleOrderEntries = `-- name: ListSaleOrderEntries :many

select sale_order_entries.sale_order_entry_id, sale_order_entries.sale_order_id, sale_order_entries.consumer_name, sale_order_entries.order_placed_date, sale_order_entries.order_status, sale_order_entries.delivered_date, sale_order_entries.sale_order_category_id, sale_order_entries.created_at, sale_order_entries.updated_at,
       sale_order_categories.category_name,
       coalesce(sum(sale_order_items.quantity * sale_order_items.price_per_unit), 0)::numeric(14, 2)
           as total_amount,
       count(sale_order_items.sale_order_item_id) as item_count
from sale_order_entries
join sale_order_categories
     on sale_order_categories.sale_order_category_id = sale_order_entries.sale_order_category_id
left join sale_order_items
     on sale_order_items.sale_order_entry_id = sale_order_entries.sale_order_entry_id
where $1::text = '' or sale_order_entries.order_status = $1::text
group by sale_order_entries.sale_order_entry_id, sale_order_categories.category_name
order by sale_order_entries.order_placed_date desc, sale_order_entries.created_at desc
`

type ListSaleOrderEntriesRow struct {
	SaleOrderEntryID    uuid.UUID          `json:"sale_order_entry_id"`
	SaleOrderID         int32              `json:"sale_order_id"`
	ConsumerName        string             `json:"consumer_name"`
	OrderPlacedDate     pgtype.Date        `json:"order_placed_date"`
	OrderStatus         string             `json:"order_status"`
	DeliveredDate       pgtype.Date        `json:"delivered_date"`
	SaleOrderCategoryID uuid.UUID          `json:"sale_order_category_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CategoryName        string             `json:"category_name"`
	TotalAmount         decimal.Decimal    `json:"total_amount"`
	ItemCount           int64              `json:"item_count"`
}

// Queries backing P6: sale order entries, the items inside them, and the
// category list they are filed under. The purchase-side equivalents live in
// orders.sql; the two are deliberately never joined.
// BR-19: total_amount is never stored, always derived.
//
// FR-P6-6 asks for a "pending only" filter. It is a parameter rather than a
// second query so the list and its filtered form cannot drift apart. Passing
// an empty status means no filter at all.
func (q *Queries) ListSaleOrderEntries(ctx context.Context, statusFilter string) ([]ListSaleOrderEntriesRow, error) {
	rows, err := q.db.Query(ctx, listSaleOrderEntries, statusFilter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSaleOrderEntriesRow{}
	for rows.Next() {
		var i ListSaleOrderEntriesRow
		if err := rows.Scan(
			&i.SaleOrderEntryID,
			&i.SaleOrderID,
			&i.ConsumerName,
			&i.OrderPlacedDate,
			&i.OrderStatus,
			&i.DeliveredDate,
			&i.SaleOrderCategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.TotalAmount,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSaleOrderItemsForEntry = `-- name: ListSaleOrderItemsForEntry :many
select sale_order_item_id, sale_order_entry_id, product_name, quantity, price_per_unit, created_at, updated_at from sale_order_items
where sale_order_entry_id = $1
order by created_at
`

func (q *Queries) ListSaleOrderItemsForEntry(ctx context.Context, saleOrderEntryID uuid.UUID) ([]SaleOrderItem, error) {
	rows, err := q.db.Query(ctx, listSaleOrderItemsForEntry, saleOrderEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SaleOrderItem{}
	for rows.Next() {
		var i SaleOrderItem
		if err := rows.Scan(
			&i.SaleOrderItemID,
			&i.SaleOrderEntryID,
			&i.ProductName,
			&i.Quantity,
			&i.PricePerUnit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignSaleOrdersToUncategorized = `-- name: ReassignSaleOrdersToUncategorized :exec
update sale_order_entries
set sale_order_category_id = (
        select uncategorized.sale_order_category_id
        from sale_order_categories as uncategorized
        where uncategorized.category_name = 'Uncategorized'
    ),
    updated_at = now()
where sale_order_entries.sale_order_category_id = $1
`

// BR-23, mirroring BR-13: deletion is never blocked. Every sale filed under
// the doomed category moves to "Uncategorized" first, so nothing dangles and
// no sale loses its place in the by-category chart.
func (q *Queries) ReassignSaleOrdersToUncategorized(ctx context.Context, saleOrderCategoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, reassignSaleOrdersToUncategorized, saleOrderCategoryID)
	return err
}

const renameSaleOrderCategory = `-- name: RenameSaleOrderCategory :one
update sale_order_categories set category_name = $2
where sale_order_category_id = $1 returning sale_order_category_id, category_name, is_system, created_at
`

type RenameSaleOrderCategoryParams struct {
	SaleOrderCategoryID uuid.UUID `json:"sale_order_category_id"`
	CategoryName        string    `json:"category_name"`
}

func (q *Queries) RenameSaleOrderCategory(ctx context.Context, arg RenameSaleOrderCategoryParams) (SaleOrderCategory, error) {
	row := q.db.QueryRow(ctx, renameSaleOrderCategory, arg.SaleOrderCategoryID, arg.CategoryName)
	var i SaleOrderCategory
	err := row.Scan(
		&i.SaleOrderCategoryID,
		&i.CategoryName,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const saleOrderIDExists = `-- name: SaleOrderIDExists :one
select exists (select 1 from sale_order_entries where sale_order_id = $1)
`

func (q *Queries) SaleOrderIDExists(ctx context.Context, saleOrderID int32) (bool, error) {
	row := q.db.QueryRow(ctx, saleOrderIDExists, saleOrderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateSaleOrderEntry = `-- name: UpdateSaleOrderEntry :one
update sale_order_entries set
    consumer_name          = $2,
    order_placed_date      = $3,
    order_status           = $4,
    delivered_date         = $5,
    sale_order_category_id = $6,
    updated_at             = now()
where sale_order_entry_id = $1
returning sale_order_entry_id, sale_order_id, consumer_name, order_placed_date, order_status, delivered_date, sale_order_category_id, created_at, updated_at
`

type UpdateSaleOrderEntryParams struct {
	SaleOrderEntryID    uuid.UUID   `json:"sale_order_entry_id"`
	ConsumerName        string      `json:"consumer_name"`
	OrderPlacedDate     pgtype.Date `json:"order_placed_date"`
	OrderStatus         string      `json:"order_status"`
	DeliveredDate       pgtype.Date `json:"delivered_date"`
	SaleOrderCategoryID uuid.UUID   `json:"sale_order_category_id"`
}

// sale_order_id is deliberately absent: it is the number the customer was
// given, so it is assigned once and never edited (BR-21).
func (q *Queries) UpdateSaleOrderEntry(ctx context.Context, arg UpdateSaleOrderEntryParams) (SaleOrderEntry, error) {
	row := q.db.QueryRow(ctx, updateSaleOrderEntry,
		arg.SaleOrderEntryID,
		arg.ConsumerName,
		arg.OrderPlacedDate,
		arg.OrderStatus,
		arg.DeliveredDate,
		arg.SaleOrderCategoryID,
	)
	var i SaleOrderEntry
	err := row.Scan(
		&i.SaleOrderEntryID,
		&i.SaleOrderID,
		&i.ConsumerName,
		&i.OrderPlacedDate,
		&i.OrderStatus,
		&i.DeliveredDate,
		&i.SaleOrderCategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSaleOrderItem = `-- name: UpdateSaleOrderItem :one
update sale_order_items set
    product_name   = $2,
    quantity       = $3,
    price_per_unit = $4,
    updated_at     = now()
where sale_order_item_id = $1
returning sale_order_item_id, sale_order_entry_id, product_name, quantity, price_per_unit, created_at, updated_at
`

type UpdateSaleOrderItemParams struct {
	SaleOrderItemID uuid.UUID       `json:"sale_order_item_id"`
	ProductName     string          `json:"product_name"`
	Quantity        int32           `json:"quantity"`
	PricePerUnit    decimal.Decimal `json:"price_per_unit"`
}

func (q *Queries) UpdateSaleOrderItem(ctx context.Context, arg UpdateSaleOrderItemParams) (SaleOrderItem, error) {
	row := q.db.QueryRow(ctx, updateSaleOrderItem,
		arg.SaleOrderItemID,
		arg.ProductName,
		arg.Quantity,
		arg.PricePerUnit,
	)
	var i SaleOrderItem
	err := row.Scan(
		&i.SaleOrderItemID,
		&i.SaleOrderEntryID,
		&i.ProductName,
		&i.Quantity,
		&i.PricePerUnit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
