// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scrape_runs.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const finishScrapeRunFailure = `-- name: FinishScrapeRunFailure :exec
update scrape_runs
set finished_at   = now(),
    run_status    = 'failed',
    error_message = $2
where scrape_run_id = $1
`

type FinishScrapeRunFailureParams struct {
	ScrapeRunID  uuid.UUID   `json:"scrape_run_id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FinishScrapeRunFailure(ctx context.Context, arg FinishScrapeRunFailureParams) error {
	_, err := q.db.Exec(ctx, finishScrapeRunFailure, arg.ScrapeRunID, arg.ErrorMessage)
	return err
}

const finishScrapeRunSuccess = `-- name: FinishScrapeRunSuccess :exec
update scrape_runs
set finished_at        = now(),
    run_status         = 'success',
    listings_seen      = $2,
    listings_updated   = $3,
    listings_delisted  = $4
where scrape_run_id = $1
`

type FinishScrapeRunSuccessParams struct {
	ScrapeRunID      uuid.UUID `json:"scrape_run_id"`
	ListingsSeen     int32     `json:"listings_seen"`
	ListingsUpdated  int32     `json:"listings_updated"`
	ListingsDelisted int32     `json:"listings_delisted"`
}

func (q *Queries) FinishScrapeRunSuccess(ctx context.Context, arg FinishScrapeRunSuccessParams) error {
	_, err := q.db.Exec(ctx, finishScrapeRunSuccess,
		arg.ScrapeRunID,
		arg.ListingsSeen,
		arg.ListingsUpdated,
		arg.ListingsDelisted,
	)
	return err
}

const listRecentScrapeRuns = `-- name: ListRecentScrapeRuns :many
select scrape_runs.scrape_run_id, scrape_runs.vendor_id, scrape_runs.started_at, scrape_runs.finished_at, scrape_runs.run_status, scrape_runs.listings_seen, scrape_runs.listings_updated, scrape_runs.listings_delisted, scrape_runs.error_message, vendors.vendor_slug, vendors.vendor_name
from scrape_runs
join vendors on vendors.vendor_id = scrape_runs.vendor_id
order by scrape_runs.started_at desc
limit $1
`

type ListRecentScrapeRunsRow struct {
	ScrapeRunID      uuid.UUID          `json:"scrape_run_id"`
	VendorID         uuid.UUID          `json:"vendor_id"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	RunStatus        string             `json:"run_status"`
	ListingsSeen     int32              `json:"listings_seen"`
	ListingsUpdated  int32              `json:"listings_updated"`
	ListingsDelisted int32              `json:"listings_delisted"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	VendorSlug       string             `json:"vendor_slug"`
	VendorName       string             `json:"vendor_name"`
}

func (q *Queries) ListRecentScrapeRuns(ctx context.Context, limit int32) ([]ListRecentScrapeRunsRow, error) {
	rows, err := q.db.Query(ctx, listRecentScrapeRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentScrapeRunsRow{}
	for rows.Next() {
		var i ListRecentScrapeRunsRow
		if err := rows.Scan(
			&i.ScrapeRunID,
			&i.VendorID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.RunStatus,
			&i.ListingsSeen,
			&i.ListingsUpdated,
			&i.ListingsDelisted,
			&i.ErrorMessage,
			&i.VendorSlug,
			&i.VendorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startScrapeRun = `-- name: StartScrapeRun :one
insert into scrape_runs (vendor_id) values ($1) returning scrape_run_id, vendor_id, started_at, finished_at, run_status, listings_seen, listings_updated, listings_delisted, error_message
`

func (q *Queries) StartScrapeRun(ctx context.Context, vendorID uuid.UUID) (ScrapeRun, error) {
	row := q.db.QueryRow(ctx, startScrapeRun, vendorID)
	var i ScrapeRun
	err := row.Scan(
		&i.ScrapeRunID,
		&i.VendorID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.RunStatus,
		&i.ListingsSeen,
		&i.ListingsUpdated,
		&i.ListingsDelisted,
		&i.ErrorMessage,
	)
	return i, err
}
