// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
insert into categories (category_name) values ($1) returning category_id, category_name, is_system, created_at
`

func (q *Queries) CreateCategory(ctx context.Context, categoryName string) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, categoryName)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryName,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createOccasionTag = `-- name: CreateOccasionTag :one
insert into occasion_tags (tag_name) values ($1) returning occasion_tag_id, tag_name, created_at
`

func (q *Queries) CreateOccasionTag(ctx context.Context, tagName string) (OccasionTag, error) {
	row := q.db.QueryRow(ctx, createOccasionTag, tagName)
	var i OccasionTag
	err := row.Scan(&i.OccasionTagID, &i.TagName, &i.CreatedAt)
	return i, err
}

const deleteAllCompareEntries = `-- name: DeleteAllCompareEntries :exec
delete from compare_entries
`

func (q *Queries) DeleteAllCompareEntries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllCompareEntries)
	return err
}

const deleteAllNonSystemCategories = `-- name: DeleteAllNonSystemCategories :exec
delete from categories where not is_system
`

func (q *Queries) DeleteAllNonSystemCategories(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllNonSystemCategories)
	return err
}

const deleteAllOccasionTags = `-- name: DeleteAllOccasionTags :exec
delete from occasion_tags
`

func (q *Queries) DeleteAllOccasionTags(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllOccasionTags)
	return err
}

const deleteAllOrderEntries = `-- name: DeleteAllOrderEntries :exec

delete from order_entries
`

// Data wipe (BR-14). Scope is the user's own records only: order entries,
// compare entries, categories and occasion tags. Vendors, listings, variants,
// MOQ tiers and price history survive, because they are not the user's data
// and, unlike orders, price history cannot be re-entered or re-scraped once
// gone. Order items and tag joins fall with their parents by cascade.
func (q *Queries) DeleteAllOrderEntries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllOrderEntries)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
delete from categories where category_id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, categoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, categoryID)
	return err
}

const deleteCategoryTagsForCategory = `-- name: DeleteCategoryTagsForCategory :exec
delete from order_item_category_tags where category_id = $1
`

// BR-13, second half: drop the old tags now that they have been re-pointed.
func (q *Queries) DeleteCategoryTagsForCategory(ctx context.Context, categoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategoryTagsForCategory, categoryID)
	return err
}

const deleteOccasionTag = `-- name: DeleteOccasionTag :exec
delete from occasion_tags where occasion_tag_id = $1
`

func (q *Queries) DeleteOccasionTag(ctx context.Context, occasionTagID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOccasionTag, occasionTagID)
	return err
}

const getCategoryByName = `-- name: GetCategoryByName :one
select category_id, category_name, is_system, created_at from categories where category_name = $1
`

func (q *Queries) GetCategoryByName(ctx context.Context, categoryName string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, categoryName)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryName,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many

select categories.category_id, categories.category_name, categories.is_system, categories.created_at,
       (select count(*) from order_item_category_tags
         where order_item_category_tags.category_id = categories.category_id) as usage_count
from categories
order by categories.is_system desc, categories.category_name
`

type ListCategoriesRow struct {
	CategoryID   uuid.UUID          `json:"category_id"`
	CategoryName string             `json:"category_name"`
	IsSystem     bool               `json:"is_system"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UsageCount   int64              `json:"usage_count"`
}

// Queries backing P5: categories, occasion tags and the data wipe.
func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOccasionTags = `-- name: ListOccasionTags :many
select occasion_tags.occasion_tag_id, occasion_tags.tag_name, occasion_tags.created_at,
       (select count(*) from order_item_occasion_tags
         where order_item_occasion_tags.occasion_tag_id = occasion_tags.occasion_tag_id) as usage_count
from occasion_tags
order by occasion_tags.tag_name
`

type ListOccasionTagsRow struct {
	OccasionTagID uuid.UUID          `json:"occasion_tag_id"`
	TagName       string             `json:"tag_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UsageCount    int64              `json:"usage_count"`
}

func (q *Queries) ListOccasionTags(ctx context.Context) ([]ListOccasionTagsRow, error) {
	rows, err := q.db.Query(ctx, listOccasionTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOccasionTagsRow{}
	for rows.Next() {
		var i ListOccasionTagsRow
		if err := rows.Scan(
			&i.OccasionTagID,
			&i.TagName,
			&i.CreatedAt,
			&i.UsageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignCategoryTagsToUncategorized = `-- name: ReassignCategoryTagsToUncategorized :exec
insert into order_item_category_tags (order_item_id, category_id)
select order_item_category_tags.order_item_id,
       (select category_id from categories where category_name = 'Uncategorized')
from order_item_category_tags
where order_item_category_tags.category_id = $1
on conflict do nothing
`

// BR-13, first half: every order item tagged with the doomed category picks up
// "Uncategorized" instead. Deletion is never blocked and no reference is left
// dangling. Kept in SQL the application drives rather than in a trigger, so the
// rule is readable in the handler that performs it.
func (q *Queries) ReassignCategoryTagsToUncategorized(ctx context.Context, categoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, reassignCategoryTagsToUncategorized, categoryID)
	return err
}

const renameCategory = `-- name: RenameCategory :one
update categories set category_name = $2 where category_id = $1 returning category_id, category_name, is_system, created_at
`

type RenameCategoryParams struct {
	CategoryID   uuid.UUID `json:"category_id"`
	CategoryName string    `json:"category_name"`
}

func (q *Queries) RenameCategory(ctx context.Context, arg RenameCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, renameCategory, arg.CategoryID, arg.CategoryName)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.CategoryName,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const renameOccasionTag = `-- name: RenameOccasionTag :one
update occasion_tags set tag_name = $2 where occasion_tag_id = $1 returning occasion_tag_id, tag_name, created_at
`

type RenameOccasionTagParams struct {
	OccasionTagID uuid.UUID `json:"occasion_tag_id"`
	TagName       string    `json:"tag_name"`
}

func (q *Queries) RenameOccasionTag(ctx context.Context, arg RenameOccasionTagParams) (OccasionTag, error) {
	row := q.db.QueryRow(ctx, renameOccasionTag, arg.OccasionTagID, arg.TagName)
	var i OccasionTag
	err := row.Scan(&i.OccasionTagID, &i.TagName, &i.CreatedAt)
	return i, err
}
