// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spend.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getMonthlySpendTrend = `-- name: GetMonthlySpendTrend :many
with trailing_months as (
    select generate_series(
        date_trunc('month', current_date) - interval '11 months',
        date_trunc('month', current_date),
        interval '1 month'
    )::date as month_start
)
select trailing_months.month_start,
       coalesce(sum(
           case
               when order_items.order_status = 'placed'
                   then order_items.quantity * order_items.price_per_unit
               when order_items.order_status = 'partially_refunded'
                   then (order_items.quantity * order_items.price_per_unit)
                        - coalesce(order_items.refund_amount, 0)
               else 0
           end
       ), 0)::numeric(14, 2) as net_spend,
       coalesce(sum(order_items.quantity * order_items.price_per_unit), 0)::numeric(14, 2) as gross_spend
from trailing_months
left join order_entries
       on date_trunc('month', order_entries.ordered_on) = trailing_months.month_start
left join order_items on order_items.order_entry_id = order_entries.order_entry_id
group by trailing_months.month_start
order by trailing_months.month_start
`

type GetMonthlySpendTrendRow struct {
	MonthStart pgtype.Date     `json:"month_start"`
	NetSpend   decimal.Decimal `json:"net_spend"`
	GrossSpend decimal.Decimal `json:"gross_spend"`
}

// FR-P4-6: always the trailing twelve months from today, deliberately ignoring
// the page's date-range filter. Months with no orders are returned as zero so
// the chart has no gaps.
func (q *Queries) GetMonthlySpendTrend(ctx context.Context) ([]GetMonthlySpendTrendRow, error) {
	rows, err := q.db.Query(ctx, getMonthlySpendTrend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlySpendTrendRow{}
	for rows.Next() {
		var i GetMonthlySpendTrendRow
		if err := rows.Scan(&i.MonthStart, &i.NetSpend, &i.GrossSpend); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpendByCategory = `-- name: GetSpendByCategory :many
with scoped_items as (
    select order_items.order_item_id,
           case
               when order_items.order_status = 'placed'
                   then order_items.quantity * order_items.price_per_unit
               when order_items.order_status = 'partially_refunded'
                   then (order_items.quantity * order_items.price_per_unit)
                        - coalesce(order_items.refund_amount, 0)
               else 0
           end as net_amount,
           order_items.quantity * order_items.price_per_unit as gross_amount
    from order_items
    join order_entries on order_entries.order_entry_id = order_items.order_entry_id
    where order_entries.ordered_on between $1 and $2
),
tag_counts as (
    select scoped_items.order_item_id,
           scoped_items.net_amount,
           scoped_items.gross_amount,
           greatest(count(order_item_category_tags.category_id), 1) as tag_count
    from scoped_items
    left join order_item_category_tags
           on order_item_category_tags.order_item_id = scoped_items.order_item_id
    group by scoped_items.order_item_id, scoped_items.net_amount, scoped_items.gross_amount
)
select coalesce(categories.category_name, 'Uncategorized')::text as category_name,
       sum(tag_counts.net_amount / tag_counts.tag_count)::numeric(14, 2)   as net_spend,
       sum(tag_counts.gross_amount / tag_counts.tag_count)::numeric(14, 2) as gross_spend
from tag_counts
left join order_item_category_tags
       on order_item_category_tags.order_item_id = tag_counts.order_item_id
left join categories on categories.category_id = order_item_category_tags.category_id
group by coalesce(categories.category_name, 'Uncategorized')
order by net_spend desc
`

type GetSpendByCategoryParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetSpendByCategoryRow struct {
	CategoryName string          `json:"category_name"`
	NetSpend     decimal.Decimal `json:"net_spend"`
	GrossSpend   decimal.Decimal `json:"gross_spend"`
}

// An order item may carry several category tags (FR-P3-8). Counting it in full
// under each would make the chart add up to more than was actually spent, so
// the amount is divided evenly between them. An item with no category at all
// is reported under "Uncategorized".
func (q *Queries) GetSpendByCategory(ctx context.Context, arg GetSpendByCategoryParams) ([]GetSpendByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getSpendByCategory, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSpendByCategoryRow{}
	for rows.Next() {
		var i GetSpendByCategoryRow
		if err := rows.Scan(&i.CategoryName, &i.NetSpend, &i.GrossSpend); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpendSummary = `-- name: GetSpendSummary :one

select
    coalesce(sum(
        case
            when order_items.order_status = 'placed'
                then order_items.quantity * order_items.price_per_unit
            when order_items.order_status = 'partially_refunded'
                then (order_items.quantity * order_items.price_per_unit)
                     - coalesce(order_items.refund_amount, 0)
            else 0
        end
    ), 0)::numeric(14, 2) as net_spend,
    coalesce(sum(order_items.quantity * order_items.price_per_unit), 0)::numeric(14, 2) as gross_spend,
    coalesce(sum(
        case when order_items.order_status in ('cancelled', 'refunded')
             then order_items.quantity * order_items.price_per_unit else 0 end
    ), 0)::numeric(14, 2) as excluded_spend,
    coalesce(sum(coalesce(order_items.refund_amount, 0)), 0)::numeric(14, 2) as refunded_amount,
    count(order_items.order_item_id) as item_count,
    count(distinct order_entries.order_entry_id) as order_count
from order_entries
left join order_items on order_items.order_entry_id = order_entries.order_entry_id
where order_entries.ordered_on between $1 and $2
`

type GetSpendSummaryParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type GetSpendSummaryRow struct {
	NetSpend       decimal.Decimal `json:"net_spend"`
	GrossSpend     decimal.Decimal `json:"gross_spend"`
	ExcludedSpend  decimal.Decimal `json:"excluded_spend"`
	RefundedAmount decimal.Decimal `json:"refunded_amount"`
	ItemCount      int64           `json:"item_count"`
	OrderCount     int64           `json:"order_count"`
}

// Queries backing P4: the spend distribution page.
//
// BR-12 governs every figure here:
//
//	Placed              counted in full
//	Partially Refunded  counted at (quantity x price) - refund_amount
//	Cancelled, Refunded excluded
//
// Each query also returns the gross figure — everything counted in full — so
// the "include cancelled and refunded" toggle (FR-P4-4) is a client-side
// switch between two numbers already in hand, not a second round trip.
//
// All date filtering uses order_entries.ordered_on, the date the order was
// actually placed, never created_at.
func (q *Queries) GetSpendSummary(ctx context.Context, arg GetSpendSummaryParams) (GetSpendSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSpendSummary, arg.StartDate, arg.EndDate)
	var i GetSpendSummaryRow
	err := row.Scan(
		&i.NetSpend,
		&i.GrossSpend,
		&i.ExcludedSpend,
		&i.RefundedAmount,
		&i.ItemCount,
		&i.OrderCount,
	)
	return i, err
}
