// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vendors.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getVendorByID = `-- name: GetVendorByID :one
select vendor_id, vendor_slug, vendor_name, source_base_url, scraper_tier, scrape_hour_utc, last_successful_scrape_timestamp, last_scrape_attempt_timestamp, last_scrape_error, created_at, updated_at from vendors where vendor_id = $1
`

func (q *Queries) GetVendorByID(ctx context.Context, vendorID uuid.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, vendorID)
	var i Vendor
	err := row.Scan(
		&i.VendorID,
		&i.VendorSlug,
		&i.VendorName,
		&i.SourceBaseUrl,
		&i.ScraperTier,
		&i.ScrapeHourUtc,
		&i.LastSuccessfulScrapeTimestamp,
		&i.LastScrapeAttemptTimestamp,
		&i.LastScrapeError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorBySlug = `-- name: GetVendorBySlug :one
select vendor_id, vendor_slug, vendor_name, source_base_url, scraper_tier, scrape_hour_utc, last_successful_scrape_timestamp, last_scrape_attempt_timestamp, last_scrape_error, created_at, updated_at from vendors where vendor_slug = $1
`

func (q *Queries) GetVendorBySlug(ctx context.Context, vendorSlug string) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorBySlug, vendorSlug)
	var i Vendor
	err := row.Scan(
		&i.VendorID,
		&i.VendorSlug,
		&i.VendorName,
		&i.SourceBaseUrl,
		&i.ScraperTier,
		&i.ScrapeHourUtc,
		&i.LastSuccessfulScrapeTimestamp,
		&i.LastScrapeAttemptTimestamp,
		&i.LastScrapeError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendors = `-- name: ListVendors :many
select vendor_id, vendor_slug, vendor_name, source_base_url, scraper_tier, scrape_hour_utc, last_successful_scrape_timestamp, last_scrape_attempt_timestamp, last_scrape_error, created_at, updated_at from vendors order by vendor_name
`

func (q *Queries) ListVendors(ctx context.Context) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.VendorID,
			&i.VendorSlug,
			&i.VendorName,
			&i.SourceBaseUrl,
			&i.ScraperTier,
			&i.ScrapeHourUtc,
			&i.LastSuccessfulScrapeTimestamp,
			&i.LastScrapeAttemptTimestamp,
			&i.LastScrapeError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorsDueForScrape = `-- name: ListVendorsDueForScrape :many
select vendor_id, vendor_slug, vendor_name, source_base_url, scraper_tier, scrape_hour_utc, last_successful_scrape_timestamp, last_scrape_attempt_timestamp, last_scrape_error, created_at, updated_at from vendors
where scraper_tier <> 'manual'
  and (
        last_successful_scrape_timestamp is null
     or last_successful_scrape_timestamp < now() - interval '23 hours'
      )
  and (
        last_successful_scrape_timestamp is null
     or extract(hour from (now() at time zone 'utc'))::int = scrape_hour_utc
     or last_successful_scrape_timestamp < now() - interval '26 hours'
      )
order by scrape_hour_utc
`

// A vendor is due when it has not had a successful run in ~a day AND either
// its hour slot is the current hour, or it is overdue enough that it clearly
// missed its slot.
//
// The generous windows are deliberate. GitHub Actions delays scheduled runs
// under load, so matching the hour exactly would silently skip a vendor whose
// slot boundary was crossed while the runner was queued; the 26-hour catch-up
// arm picks it up on the next hourly tick instead of a day later.
func (q *Queries) ListVendorsDueForScrape(ctx context.Context) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendorsDueForScrape)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.VendorID,
			&i.VendorSlug,
			&i.VendorName,
			&i.SourceBaseUrl,
			&i.ScraperTier,
			&i.ScrapeHourUtc,
			&i.LastSuccessfulScrapeTimestamp,
			&i.LastScrapeAttemptTimestamp,
			&i.LastScrapeError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVendorScrapeAttempt = `-- name: MarkVendorScrapeAttempt :exec
update vendors
set last_scrape_attempt_timestamp = now(), updated_at = now()
where vendor_id = $1
`

func (q *Queries) MarkVendorScrapeAttempt(ctx context.Context, vendorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markVendorScrapeAttempt, vendorID)
	return err
}

const markVendorScrapeFailure = `-- name: MarkVendorScrapeFailure :exec
update vendors
set last_scrape_error = $2, updated_at = now()
where vendor_id = $1
`

type MarkVendorScrapeFailureParams struct {
	VendorID        uuid.UUID   `json:"vendor_id"`
	LastScrapeError pgtype.Text `json:"last_scrape_error"`
}

func (q *Queries) MarkVendorScrapeFailure(ctx context.Context, arg MarkVendorScrapeFailureParams) error {
	_, err := q.db.Exec(ctx, markVendorScrapeFailure, arg.VendorID, arg.LastScrapeError)
	return err
}

const markVendorScrapeSuccess = `-- name: MarkVendorScrapeSuccess :exec
update vendors
set last_successful_scrape_timestamp = now(), last_scrape_error = null, updated_at = now()
where vendor_id = $1
`

func (q *Queries) MarkVendorScrapeSuccess(ctx context.Context, vendorID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markVendorScrapeSuccess, vendorID)
	return err
}

const upsertVendorFromConfig = `-- name: UpsertVendorFromConfig :one
insert into vendors (vendor_slug, vendor_name, source_base_url, scraper_tier, scrape_hour_utc)
values ($1, $2, $3, $4, $5)
on conflict (vendor_slug) do update set
    vendor_name     = excluded.vendor_name,
    source_base_url = excluded.source_base_url,
    scraper_tier    = excluded.scraper_tier,
    scrape_hour_utc = excluded.scrape_hour_utc,
    updated_at      = now()
returning vendor_id, vendor_slug, vendor_name, source_base_url, scraper_tier, scrape_hour_utc, last_successful_scrape_timestamp, last_scrape_attempt_timestamp, last_scrape_error, created_at, updated_at
`

type UpsertVendorFromConfigParams struct {
	VendorSlug    string `json:"vendor_slug"`
	VendorName    string `json:"vendor_name"`
	SourceBaseUrl string `json:"source_base_url"`
	ScraperTier   string `json:"scraper_tier"`
	ScrapeHourUtc int16  `json:"scrape_hour_utc"`
}

// config/vendors.go is the source of truth for the registry; this keeps the
// vendors table in step with it on every run so the two never drift.
func (q *Queries) UpsertVendorFromConfig(ctx context.Context, arg UpsertVendorFromConfigParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, upsertVendorFromConfig,
		arg.VendorSlug,
		arg.VendorName,
		arg.SourceBaseUrl,
		arg.ScraperTier,
		arg.ScrapeHourUtc,
	)
	var i Vendor
	err := row.Scan(
		&i.VendorID,
		&i.VendorSlug,
		&i.VendorName,
		&i.SourceBaseUrl,
		&i.ScraperTier,
		&i.ScrapeHourUtc,
		&i.LastSuccessfulScrapeTimestamp,
		&i.LastScrapeAttemptTimestamp,
		&i.LastScrapeError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
