// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Category struct {
	CategoryID   uuid.UUID          `json:"category_id"`
	CategoryName string             `json:"category_name"`
	IsSystem     bool               `json:"is_system"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type CompareEntry struct {
	CompareEntryID uuid.UUID          `json:"compare_entry_id"`
	EntryName      string             `json:"entry_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CompareEntryMember struct {
	CompareEntryMemberID uuid.UUID          `json:"compare_entry_member_id"`
	CompareEntryID       uuid.UUID          `json:"compare_entry_id"`
	VendorListingID      uuid.NullUUID      `json:"vendor_listing_id"`
	VariantID            uuid.NullUUID      `json:"variant_id"`
	AddedAt              pgtype.Timestamptz `json:"added_at"`
}

type MoqTier struct {
	MoqTierID            uuid.UUID           `json:"moq_tier_id"`
	VendorListingID      uuid.NullUUID       `json:"vendor_listing_id"`
	VariantID            uuid.NullUUID       `json:"variant_id"`
	QuantityRangeMinimum int32               `json:"quantity_range_minimum"`
	QuantityRangeMaximum pgtype.Int4         `json:"quantity_range_maximum"`
	PricePerUnit         decimal.Decimal     `json:"price_per_unit"`
	DiscountPercent      decimal.NullDecimal `json:"discount_percent"`
	CreatedAt            pgtype.Timestamptz  `json:"created_at"`
}

type OccasionTag struct {
	OccasionTagID uuid.UUID          `json:"occasion_tag_id"`
	TagName       string             `json:"tag_name"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type OrderEntry struct {
	OrderEntryID uuid.UUID          `json:"order_entry_id"`
	EntryName    pgtype.Text        `json:"entry_name"`
	OrderedOn    pgtype.Date        `json:"ordered_on"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	OrderItemID         uuid.UUID           `json:"order_item_id"`
	OrderEntryID        uuid.UUID           `json:"order_entry_id"`
	VendorListingID     uuid.NullUUID       `json:"vendor_listing_id"`
	VariantID           uuid.NullUUID       `json:"variant_id"`
	VendorID            uuid.UUID           `json:"vendor_id"`
	ListingNameSnapshot string              `json:"listing_name_snapshot"`
	Quantity            int32               `json:"quantity"`
	PricePerUnit        decimal.Decimal     `json:"price_per_unit"`
	OrderStatus         string              `json:"order_status"`
	RefundAmount        decimal.NullDecimal `json:"refund_amount"`
	Rating              pgtype.Int4         `json:"rating"`
	CreatedAt           pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz  `json:"updated_at"`
}

type OrderItemCategoryTag struct {
	OrderItemID uuid.UUID `json:"order_item_id"`
	CategoryID  uuid.UUID `json:"category_id"`
}

type OrderItemOccasionTag struct {
	OrderItemID   uuid.UUID `json:"order_item_id"`
	OccasionTagID uuid.UUID `json:"occasion_tag_id"`
}

type PriceHistoryEntry struct {
	PriceHistoryEntryID uuid.UUID          `json:"price_history_entry_id"`
	VendorListingID     uuid.NullUUID      `json:"vendor_listing_id"`
	VariantID           uuid.NullUUID      `json:"variant_id"`
	ScrapedAtDate       pgtype.Date        `json:"scraped_at_date"`
	Price               decimal.Decimal    `json:"price"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ScrapeRun struct {
	ScrapeRunID      uuid.UUID          `json:"scrape_run_id"`
	VendorID         uuid.UUID          `json:"vendor_id"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
	RunStatus        string             `json:"run_status"`
	ListingsSeen     int32              `json:"listings_seen"`
	ListingsUpdated  int32              `json:"listings_updated"`
	ListingsDelisted int32              `json:"listings_delisted"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
}

type Variant struct {
	VariantID          uuid.UUID           `json:"variant_id"`
	VendorListingID    uuid.UUID           `json:"vendor_listing_id"`
	VariantLabel       string              `json:"variant_label"`
	ExternalVariantID  pgtype.Text         `json:"external_variant_id"`
	VariantSku         pgtype.Text         `json:"variant_sku"`
	IsInStock          bool                `json:"is_in_stock"`
	IsDelisted         bool                `json:"is_delisted"`
	DelistedAt         pgtype.Timestamptz  `json:"delisted_at"`
	LastSeenAt         pgtype.Timestamptz  `json:"last_seen_at"`
	PackSize           pgtype.Int4         `json:"pack_size"`
	CurrentPrice       decimal.NullDecimal `json:"current_price"`
	PreviousPrice      decimal.NullDecimal `json:"previous_price"`
	PriceLastChangedAt pgtype.Timestamptz  `json:"price_last_changed_at"`
	CreatedAt          pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `json:"updated_at"`
}

type Vendor struct {
	VendorID                      uuid.UUID          `json:"vendor_id"`
	VendorSlug                    string             `json:"vendor_slug"`
	VendorName                    string             `json:"vendor_name"`
	SourceBaseUrl                 string             `json:"source_base_url"`
	ScraperTier                   string             `json:"scraper_tier"`
	ScrapeHourUtc                 int16              `json:"scrape_hour_utc"`
	LastSuccessfulScrapeTimestamp pgtype.Timestamptz `json:"last_successful_scrape_timestamp"`
	LastScrapeAttemptTimestamp    pgtype.Timestamptz `json:"last_scrape_attempt_timestamp"`
	LastScrapeError               pgtype.Text        `json:"last_scrape_error"`
	CreatedAt                     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                     pgtype.Timestamptz `json:"updated_at"`
}

type VendorListing struct {
	VendorListingID    uuid.UUID           `json:"vendor_listing_id"`
	VendorID           uuid.UUID           `json:"vendor_id"`
	ProductUrl         string              `json:"product_url"`
	ExternalProductID  pgtype.Text         `json:"external_product_id"`
	ListingName        string              `json:"listing_name"`
	Description        pgtype.Text         `json:"description"`
	PrimaryImageUrl    pgtype.Text         `json:"primary_image_url"`
	VendorSideCategory pgtype.Text         `json:"vendor_side_category"`
	VendorSideSku      pgtype.Text         `json:"vendor_side_sku"`
	IsInStock          bool                `json:"is_in_stock"`
	HasVariants        bool                `json:"has_variants"`
	IsTracked          bool                `json:"is_tracked"`
	IsDelisted         bool                `json:"is_delisted"`
	DelistedAt         pgtype.Timestamptz  `json:"delisted_at"`
	LastSeenAt         pgtype.Timestamptz  `json:"last_seen_at"`
	PackSize           pgtype.Int4         `json:"pack_size"`
	CurrentPrice       decimal.NullDecimal `json:"current_price"`
	PreviousPrice      decimal.NullDecimal `json:"previous_price"`
	PriceLastChangedAt pgtype.Timestamptz  `json:"price_last_changed_at"`
	CreatedAt          pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz  `json:"updated_at"`
}
