// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moq_tiers.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const deleteMoqTiersForListing = `-- name: DeleteMoqTiersForListing :exec
delete from moq_tiers where vendor_listing_id = $1
`

// Tier ladders are three or four rows, so a deep scrape replaces the whole
// set inside one transaction rather than diffing row by row.
func (q *Queries) DeleteMoqTiersForListing(ctx context.Context, vendorListingID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteMoqTiersForListing, vendorListingID)
	return err
}

const deleteMoqTiersForVariant = `-- name: DeleteMoqTiersForVariant :exec
delete from moq_tiers where variant_id = $1
`

func (q *Queries) DeleteMoqTiersForVariant(ctx context.Context, variantID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteMoqTiersForVariant, variantID)
	return err
}

const insertListingMoqTier = `-- name: InsertListingMoqTier :one
insert into moq_tiers (
    vendor_listing_id, quantity_range_minimum, quantity_range_maximum,
    price_per_unit, discount_percent
) values ($1, $2, $3, $4, $5)
returning moq_tier_id, vendor_listing_id, variant_id, quantity_range_minimum, quantity_range_maximum, price_per_unit, discount_percent, created_at
`

type InsertListingMoqTierParams struct {
	VendorListingID      uuid.NullUUID       `json:"vendor_listing_id"`
	QuantityRangeMinimum int32               `json:"quantity_range_minimum"`
	QuantityRangeMaximum pgtype.Int4         `json:"quantity_range_maximum"`
	PricePerUnit         decimal.Decimal     `json:"price_per_unit"`
	DiscountPercent      decimal.NullDecimal `json:"discount_percent"`
}

func (q *Queries) InsertListingMoqTier(ctx context.Context, arg InsertListingMoqTierParams) (MoqTier, error) {
	row := q.db.QueryRow(ctx, insertListingMoqTier,
		arg.VendorListingID,
		arg.QuantityRangeMinimum,
		arg.QuantityRangeMaximum,
		arg.PricePerUnit,
		arg.DiscountPercent,
	)
	var i MoqTier
	err := row.Scan(
		&i.MoqTierID,
		&i.VendorListingID,
		&i.VariantID,
		&i.QuantityRangeMinimum,
		&i.QuantityRangeMaximum,
		&i.PricePerUnit,
		&i.DiscountPercent,
		&i.CreatedAt,
	)
	return i, err
}

const insertVariantMoqTier = `-- name: InsertVariantMoqTier :one
insert into moq_tiers (
    variant_id, quantity_range_minimum, quantity_range_maximum,
    price_per_unit, discount_percent
) values ($1, $2, $3, $4, $5)
returning moq_tier_id, vendor_listing_id, variant_id, quantity_range_minimum, quantity_range_maximum, price_per_unit, discount_percent, created_at
`

type InsertVariantMoqTierParams struct {
	VariantID            uuid.NullUUID       `json:"variant_id"`
	QuantityRangeMinimum int32               `json:"quantity_range_minimum"`
	QuantityRangeMaximum pgtype.Int4         `json:"quantity_range_maximum"`
	PricePerUnit         decimal.Decimal     `json:"price_per_unit"`
	DiscountPercent      decimal.NullDecimal `json:"discount_percent"`
}

func (q *Queries) InsertVariantMoqTier(ctx context.Context, arg InsertVariantMoqTierParams) (MoqTier, error) {
	row := q.db.QueryRow(ctx, insertVariantMoqTier,
		arg.VariantID,
		arg.QuantityRangeMinimum,
		arg.QuantityRangeMaximum,
		arg.PricePerUnit,
		arg.DiscountPercent,
	)
	var i MoqTier
	err := row.Scan(
		&i.MoqTierID,
		&i.VendorListingID,
		&i.VariantID,
		&i.QuantityRangeMinimum,
		&i.QuantityRangeMaximum,
		&i.PricePerUnit,
		&i.DiscountPercent,
		&i.CreatedAt,
	)
	return i, err
}

const listMoqTiersForListing = `-- name: ListMoqTiersForListing :many
select moq_tier_id, vendor_listing_id, variant_id, quantity_range_minimum, quantity_range_maximum, price_per_unit, discount_percent, created_at from moq_tiers
where vendor_listing_id = $1
order by quantity_range_minimum
`

func (q *Queries) ListMoqTiersForListing(ctx context.Context, vendorListingID uuid.NullUUID) ([]MoqTier, error) {
	rows, err := q.db.Query(ctx, listMoqTiersForListing, vendorListingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MoqTier{}
	for rows.Next() {
		var i MoqTier
		if err := rows.Scan(
			&i.MoqTierID,
			&i.VendorListingID,
			&i.VariantID,
			&i.QuantityRangeMinimum,
			&i.QuantityRangeMaximum,
			&i.PricePerUnit,
			&i.DiscountPercent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMoqTiersForVariant = `-- name: ListMoqTiersForVariant :many
select moq_tier_id, vendor_listing_id, variant_id, quantity_range_minimum, quantity_range_maximum, price_per_unit, discount_percent, created_at from moq_tiers
where variant_id = $1
order by quantity_range_minimum
`

func (q *Queries) ListMoqTiersForVariant(ctx context.Context, variantID uuid.NullUUID) ([]MoqTier, error) {
	rows, err := q.db.Query(ctx, listMoqTiersForVariant, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MoqTier{}
	for rows.Next() {
		var i MoqTier
		if err := rows.Scan(
			&i.MoqTierID,
			&i.VendorListingID,
			&i.VariantID,
			&i.QuantityRangeMinimum,
			&i.QuantityRangeMaximum,
			&i.PricePerUnit,
			&i.DiscountPercent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
