// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price_history.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const listPriceHistoryForListing = `-- name: ListPriceHistoryForListing :many
select scraped_at_date, price
from price_history_entries
where vendor_listing_id = $1
order by scraped_at_date
`

type ListPriceHistoryForListingRow struct {
	ScrapedAtDate pgtype.Date     `json:"scraped_at_date"`
	Price         decimal.Decimal `json:"price"`
}

func (q *Queries) ListPriceHistoryForListing(ctx context.Context, vendorListingID uuid.NullUUID) ([]ListPriceHistoryForListingRow, error) {
	rows, err := q.db.Query(ctx, listPriceHistoryForListing, vendorListingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceHistoryForListingRow{}
	for rows.Next() {
		var i ListPriceHistoryForListingRow
		if err := rows.Scan(&i.ScrapedAtDate, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceHistoryForVariant = `-- name: ListPriceHistoryForVariant :many
select scraped_at_date, price
from price_history_entries
where variant_id = $1
order by scraped_at_date
`

type ListPriceHistoryForVariantRow struct {
	ScrapedAtDate pgtype.Date     `json:"scraped_at_date"`
	Price         decimal.Decimal `json:"price"`
}

func (q *Queries) ListPriceHistoryForVariant(ctx context.Context, variantID uuid.NullUUID) ([]ListPriceHistoryForVariantRow, error) {
	rows, err := q.db.Query(ctx, listPriceHistoryForVariant, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPriceHistoryForVariantRow{}
	for rows.Next() {
		var i ListPriceHistoryForVariantRow
		if err := rows.Scan(&i.ScrapedAtDate, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertListingPriceHistory = `-- name: UpsertListingPriceHistory :exec
insert into price_history_entries (vendor_listing_id, scraped_at_date, price)
values ($1, $2, $3)
on conflict (vendor_listing_id, scraped_at_date) where vendor_listing_id is not null
do update set price = excluded.price
`

type UpsertListingPriceHistoryParams struct {
	VendorListingID uuid.NullUUID   `json:"vendor_listing_id"`
	ScrapedAtDate   pgtype.Date     `json:"scraped_at_date"`
	Price           decimal.Decimal `json:"price"`
}

// One row per listing per day. The upsert respects BR-3's append-only intent:
// earlier days are never touched, only today's row is corrected if the same
// day is scraped twice.
func (q *Queries) UpsertListingPriceHistory(ctx context.Context, arg UpsertListingPriceHistoryParams) error {
	_, err := q.db.Exec(ctx, upsertListingPriceHistory, arg.VendorListingID, arg.ScrapedAtDate, arg.Price)
	return err
}

const upsertVariantPriceHistory = `-- name: UpsertVariantPriceHistory :exec
insert into price_history_entries (variant_id, scraped_at_date, price)
values ($1, $2, $3)
on conflict (variant_id, scraped_at_date) where variant_id is not null
do update set price = excluded.price
`

type UpsertVariantPriceHistoryParams struct {
	VariantID     uuid.NullUUID   `json:"variant_id"`
	ScrapedAtDate pgtype.Date     `json:"scraped_at_date"`
	Price         decimal.Decimal `json:"price"`
}

func (q *Queries) UpsertVariantPriceHistory(ctx context.Context, arg UpsertVariantPriceHistoryParams) error {
	_, err := q.db.Exec(ctx, upsertVariantPriceHistory, arg.VariantID, arg.ScrapedAtDate, arg.Price)
	return err
}
